=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_14/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "status": {
            "type": "string"
        },
        "policy": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "description",
                "name"
            ]
        },
        "findingKey": {
            "type": "string"
        },
        "findingId": {
            "type": "string"
        },
        "cloudGuardAccountId": {
            "type": "string"
        },
        "origin": {
            "type": "string"
        },
        "bundle": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            },
            "required": [
                "description",
                "id",
                "name"
            ]
        },
        "reportTime": {
            "type": "string"
        },
        "rule": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "ruleId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "remediation": {
                    "type": "string"
                },
                "complianceTags": {
                    "type": "string"
                },
                "logicHash": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                }
            },
            "required": [
                "complianceTags",
                "description",
                "logicHash",
                "name",
                "remediation",
                "ruleId",
                "severity"
            ]
        },
        "account": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                },
                "dome9CloudAccountId": {
                    "type": "string"
                },
                "organizationalUnitId": {
                    "type": "string"
                },
                "organizationalUnitPath": {
                    "type": "string"
                }
            },
            "required": [
                "dome9CloudAccountId",
                "id",
                "name",
                "organizationalUnitId",
                "organizationalUnitPath",
                "vendor"
            ]
        },
        "region": {
            "type": "string"
        },
        "entity": {
            "type": "object",
            "properties": {
                "subjects": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "apiGroup": {
                                "type": "null"
                            },
                            "kind": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string"
                            },
                            "namespace": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "apiGroup",
                            "kind",
                            "name",
                            "namespace"
                        ]
                    }
                },
                "role": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "rules": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "apiGroups": {
                                        "anyOf": [
                                            {
                                                "type": "null"
                                            },
                                            {
                                                "type": "array",
                                                "items": {
                                                    "type": "string"
                                                }
                                            }
                                        ]
                                    },
                                    "nonResourceURLs": {
                                        "anyOf": [
                                            {
                                                "type": "null"
                                            },
                                            {
                                                "type": "array",
                                                "items": {
                                                    "type": "string"
                                                }
                                            }
                                        ]
                                    },
                                    "resourceNames": {
                                        "type": "null"
                                    },
                                    "resources": {
                                        "anyOf": [
                                            {
                                                "type": "null"
                                            },
                                            {
                                                "type": "array",
                                                "items": {
                                                    "type": "string"
                                                }
                                            }
                                        ]
                                    },
                                    "verbs": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "required": [
                                    "apiGroups",
                                    "nonResourceURLs",
                                    "resourceNames",
                                    "resources",
                                    "verbs"
                                ]
                            }
                        },
                        "aggregationRule": {
                            "type": "null"
                        },
                        "kind": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "aggregationRule",
                        "kind",
                        "name",
                        "rules"
                    ]
                },
                "kind": {
                    "type": "string"
                },
                "tags": {
                    "type": "array"
                },
                "namespace": {
                    "type": "string"
                },
                "annotations": {
                    "type": "array"
                },
                "labels": {
                    "type": "array"
                },
                "creationTime": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "dome9Id": {
                    "type": "string"
                },
                "accountNumber": {
                    "type": "string"
                },
                "assetLabels": {
                    "type": "null"
                },
                "region": {
                    "type": "string"
                },
                "externalFindings": {
                    "type": "null"
                }
            },
            "required": [
                "accountNumber",
                "annotations",
                "assetLabels",
                "creationTime",
                "dome9Id",
                "externalFindings",
                "id",
                "kind",
                "labels",
                "name",
                "namespace",
                "region",
                "role",
                "subjects",
                "tags",
                "type"
            ]
        },
        "remediationActions": {
            "type": "array"
        },
        "action": {
            "type": "string"
        },
        "additionalFields": {
            "type": "array"
        }
    },
    "required": [
        "account",
        "action",
        "additionalFields",
        "bundle",
        "cloudGuardAccountId",
        "entity",
        "findingId",
        "findingKey",
        "origin",
        "policy",
        "region",
        "remediationActions",
        "reportTime",
        "rule",
        "status"
    ]
}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/webhook-1686308471241.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"9O3Zf9NcFAUleKrX7JtYmg","findingId":"9O3Zf9NcFAUleKrX7JtYmg","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"CIS Kubernetes Benchmark v1.6.1","description":"Automated Validation of Kubernetes CIS Benchmark v1.6.1 Prescriptive guidance for establishing a secure configuration posture for Kubernetes 1.6.1\nFor additional reference: https://www.cisecurity.org/benchmark/kubernetes/","id":-70},"reportTime":"2023-06-09T11:00:31.243Z","rule":{"name":"Minimize access to create pods (RBAC)","ruleId":"D9.K8S.IAM.35","description":"The ability to create pods in a namespace can provide a number of opportunities for privilege escalation, such as assigning privileged service accounts to these pods or mounting hostPaths with access to sensitive data (unless Pod Security Policies are implemented to restrict this access). As such, access to create new pods should be restricted to the smallest possible group of users. The ability to create pods in a cluster opens up possibilities for privilege escalation and should be restricted, where possible.","remediation":"Where possible, remove create access to pod objects in the cluster.","complianceTags":"5.1.4","logicHash":"grYFwC76VTIueiiCNKmvrw","severity":"Low"},"account":{"id":"5af13ab5-72ed-43b6-9544-33c9236d62f0","name":"nu-openshift-cluster","vendor":"Kubernetes","dome9CloudAccountId":"5af13ab5-72ed-43b6-9544-33c9236d62f0","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"subjects":[{"apiGroup":null,"kind":"ServiceAccount","name":"etcd-operator","namespace":"openshift-etcd-operator"}],"role":{"name":"cluster-admin","rules":[{"apiGroups":["*"],"nonResourceURLs":null,"resourceNames":null,"resources":["*"],"verbs":["*"]},{"apiGroups":null,"nonResourceURLs":["*"],"resourceNames":null,"resources":null,"verbs":["*"]}],"aggregationRule":null,"kind":"ClusterRole"},"kind":"ClusterRoleBinding","tags":[],"namespace":"*","annotations":[{"key":"include.release.openshift.io/self-managed-high-availability","value":"true"},{"key":"include.release.openshift.io/single-node-developer","value":"true"}],"labels":[],"creationTime":1667113730,"id":"f8746a33-38fc-4fd0-97a3-12404ca153a1","type":"KubernetesRoleBinding","name":"system:openshift:operator:etcd-operator","dome9Id":"11|5af13ab5-72ed-43b6-9544-33c9236d62f0|ClusterRoleBinding|f8746a33-38fc-4fd0-97a3-12404ca153a1","accountNumber":"5af13ab5-72ed-43b6-9544-33c9236d62f0","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_59/webhook-1686308537824.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"MaSTQSYD/1Fj24z/cumx6Q","findingId":"MaSTQSYD/1Fj24z/cumx6Q","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"CIS Kubernetes Benchmark v1.6.1","description":"Automated Validation of Kubernetes CIS Benchmark v1.6.1 Prescriptive guidance for establishing a secure configuration posture for Kubernetes 1.6.1\nFor additional reference: https://www.cisecurity.org/benchmark/kubernetes/","id":-70},"reportTime":"2023-06-09T11:00:31.243Z","rule":{"name":"Minimize access to create pods (RBAC)","ruleId":"D9.K8S.IAM.35","description":"The ability to create pods in a namespace can provide a number of opportunities for privilege escalation, such as assigning privileged service accounts to these pods or mounting hostPaths with access to sensitive data (unless Pod Security Policies are implemented to restrict this access). As such, access to create new pods should be restricted to the smallest possible group of users. The ability to create pods in a cluster opens up possibilities for privilege escalation and should be restricted, where possible.","remediation":"Where possible, remove create access to pod objects in the cluster.","complianceTags":"5.1.4","logicHash":"grYFwC76VTIueiiCNKmvrw","severity":"Low"},"account":{"id":"5af13ab5-72ed-43b6-9544-33c9236d62f0","name":"nu-openshift-cluster","vendor":"Kubernetes","dome9CloudAccountId":"5af13ab5-72ed-43b6-9544-33c9236d62f0","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"subjects":[{"apiGroup":null,"kind":"ServiceAccount","name":"cluster-node-tuning-operator","namespace":"openshift-cluster-node-tuning-operator"}],"role":{"name":"cluster-node-tuning-operator","rules":[{"apiGroups":["tuned.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["tuneds"],"verbs":["create","get","delete","list","update","watch","patch"]},{"apiGroups":["tuned.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["tuneds/finalizers"],"verbs":["update"]},{"apiGroups":["tuned.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["profiles"],"verbs":["create","get","delete","list","update","watch","patch"]},{"apiGroups":["tuned.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["profiles/finalizers"],"verbs":["update"]},{"apiGroups":["apps"],"nonResourceURLs":null,"resourceNames":null,"resources":["daemonsets"],"verbs":["create","get","delete","list","update","watch"]},{"apiGroups":["security.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["securitycontextconstraints"],"verbs":["use"]},{"apiGroups":[""],"nonResourceURLs":null,"resourceNames":null,"resources":["configmaps","events"],"verbs":["create","get","delete","list","update","watch","patch"]},{"apiGroups":[""],"nonResourceURLs":null,"resourceNames":null,"resources":["nodes","pods"],"verbs":["get","list","watch"]},{"apiGroups":[""],"nonResourceURLs":null,"resourceNames":null,"resources":["nodes/metrics","nodes/specs"],"verbs":["get"]},{"apiGroups":["config.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["clusteroperators","infrastructures"],"verbs":["create","get","list","watch"]},{"apiGroups":["config.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["clusteroperators/status","clusteroperators/finalizers"],"verbs":["update"]},{"apiGroups":["machineconfiguration.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["kubeletconfigs","machineconfigs"],"verbs":["create","get","delete","list","update","watch"]},{"apiGroups":["machineconfiguration.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["machineconfigpools"],"verbs":["get","list","watch"]},{"apiGroups":["coordination.k8s.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["leases"],"verbs":["create","get","update","patch"]},{"apiGroups":["node.k8s.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["runtimeclasses"],"verbs":["create","get","delete","list","update","watch"]},{"apiGroups":["performance.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["*"],"verbs":["*"]},{"apiGroups":["operators.coreos.com"],"nonResourceURLs":null,"resourceNames":null,"resources":["clusterserviceversions","operatorgroups","subscriptions"],"verbs":["get","delete","list","update","watch"]}],"aggregationRule":null,"kind":"ClusterRole"},"kind":"ClusterRoleBinding","tags":[],"namespace":"*","annotations":[{"key":"include.release.openshift.io/ibm-cloud-managed","value":"true"},{"key":"include.release.openshift.io/self-managed-high-availability","value":"true"},{"key":"include.release.openshift.io/single-node-developer","value":"true"}],"labels":[],"creationTime":1667113738,"id":"67e1a628-b828-473f-82b0-2cd6192fd3e2","type":"KubernetesRoleBinding","name":"cluster-node-tuning-operator","dome9Id":"11|5af13ab5-72ed-43b6-9544-33c9236d62f0|ClusterRoleBinding|67e1a628-b828-473f-82b0-2cd6192fd3e2","accountNumber":"5af13ab5-72ed-43b6-9544-33c9236d62f0","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}
