=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_14/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "status": {
            "type": "string"
        },
        "policy": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "description",
                "name"
            ]
        },
        "findingKey": {
            "type": "string"
        },
        "findingId": {
            "type": "string"
        },
        "cloudGuardAccountId": {
            "type": "string"
        },
        "origin": {
            "type": "string"
        },
        "bundle": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            },
            "required": [
                "description",
                "id",
                "name"
            ]
        },
        "reportTime": {
            "type": "string"
        },
        "rule": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "ruleId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "remediation": {
                    "type": "string"
                },
                "complianceTags": {
                    "type": "string"
                },
                "logicHash": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                }
            },
            "required": [
                "complianceTags",
                "description",
                "logicHash",
                "name",
                "remediation",
                "ruleId",
                "severity"
            ]
        },
        "account": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                },
                "dome9CloudAccountId": {
                    "type": "string"
                },
                "organizationalUnitId": {
                    "type": "string"
                },
                "organizationalUnitPath": {
                    "type": "string"
                }
            },
            "required": [
                "dome9CloudAccountId",
                "id",
                "name",
                "organizationalUnitId",
                "organizationalUnitPath",
                "vendor"
            ]
        },
        "region": {
            "type": "string"
        },
        "entity": {
            "type": "object",
            "properties": {
                "subjects": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "apiGroup": {
                                "type": "null"
                            },
                            "kind": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string"
                            },
                            "namespace": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "apiGroup",
                            "kind",
                            "name",
                            "namespace"
                        ]
                    }
                },
                "role": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "rules": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "apiGroups": {
                                        "anyOf": [
                                            {
                                                "type": "null"
                                            },
                                            {
                                                "type": "array",
                                                "items": {
                                                    "type": "string"
                                                }
                                            }
                                        ]
                                    },
                                    "nonResourceURLs": {
                                        "anyOf": [
                                            {
                                                "type": "null"
                                            },
                                            {
                                                "type": "array",
                                                "items": {
                                                    "type": "string"
                                                }
                                            }
                                        ]
                                    },
                                    "resourceNames": {
                                        "type": "null"
                                    },
                                    "resources": {
                                        "anyOf": [
                                            {
                                                "type": "null"
                                            },
                                            {
                                                "type": "array",
                                                "items": {
                                                    "type": "string"
                                                }
                                            }
                                        ]
                                    },
                                    "verbs": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "required": [
                                    "apiGroups",
                                    "nonResourceURLs",
                                    "resourceNames",
                                    "resources",
                                    "verbs"
                                ]
                            }
                        },
                        "aggregationRule": {
                            "type": "null"
                        },
                        "kind": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "aggregationRule",
                        "kind",
                        "name",
                        "rules"
                    ]
                },
                "kind": {
                    "type": "string"
                },
                "tags": {
                    "type": "array"
                },
                "namespace": {
                    "type": "string"
                },
                "annotations": {
                    "type": "array"
                },
                "labels": {
                    "type": "array"
                },
                "creationTime": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "dome9Id": {
                    "type": "string"
                },
                "accountNumber": {
                    "type": "string"
                },
                "assetLabels": {
                    "type": "null"
                },
                "region": {
                    "type": "string"
                },
                "externalFindings": {
                    "type": "null"
                }
            },
            "required": [
                "accountNumber",
                "annotations",
                "assetLabels",
                "creationTime",
                "dome9Id",
                "externalFindings",
                "id",
                "kind",
                "labels",
                "name",
                "namespace",
                "region",
                "role",
                "subjects",
                "tags",
                "type"
            ]
        },
        "remediationActions": {
            "type": "array"
        },
        "action": {
            "type": "string"
        },
        "additionalFields": {
            "type": "array"
        }
    },
    "required": [
        "account",
        "action",
        "additionalFields",
        "bundle",
        "cloudGuardAccountId",
        "entity",
        "findingId",
        "findingKey",
        "origin",
        "policy",
        "region",
        "remediationActions",
        "reportTime",
        "rule",
        "status"
    ]
}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/webhook-1686308546814.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"nwi/Bg62bjfuYDm+FEMKmQ","findingId":"nwi/Bg62bjfuYDm+FEMKmQ","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"CIS Kubernetes Benchmark v1.6.1","description":"Automated Validation of Kubernetes CIS Benchmark v1.6.1 Prescriptive guidance for establishing a secure configuration posture for Kubernetes 1.6.1\nFor additional reference: https://www.cisecurity.org/benchmark/kubernetes/","id":-70},"reportTime":"2023-06-09T11:00:31.243Z","rule":{"name":"Ensure that default service accounts are not actively used. (RBAC)","ruleId":"D9.K8S.IAM.36","description":"The default service account should not be used to ensure that rights granted to applications can be more easily audited and reviewed. Kubernetes provides a default service account which is used by cluster workloads where no specific service account is assigned to the pod. Where access to the Kubernetes API from a pod is required, a specific service account should be created for that pod, and rights granted to that service account. The default service account should be configured such that it does not provide a service account token and does not have any explicit rights assignments.","remediation":"Create explicit service accounts wherever a Kubernetes workload requires specific access to the Kubernetes API server. Modify the configuration of each default service account to include this value:\nautomountServiceAccountToken: false\n\n**References**\n1. https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/\n2. https://aws.github.io/aws-eks-best-practices/iam/#disable-auto-mounting-ofservice-account-tokens (EKS) ","complianceTags":"5.1.5","logicHash":"iyh0kLFb/m3DBPWpu8MYrg","severity":"Low"},"account":{"id":"5af13ab5-72ed-43b6-9544-33c9236d62f0","name":"nu-openshift-cluster","vendor":"Kubernetes","dome9CloudAccountId":"5af13ab5-72ed-43b6-9544-33c9236d62f0","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"subjects":[{"apiGroup":null,"kind":"ServiceAccount","name":"default","namespace":"openshift-network-operator"}],"role":{"name":"cluster-admin","rules":[{"apiGroups":["*"],"nonResourceURLs":null,"resourceNames":null,"resources":["*"],"verbs":["*"]},{"apiGroups":null,"nonResourceURLs":["*"],"resourceNames":null,"resources":null,"verbs":["*"]}],"aggregationRule":null,"kind":"ClusterRole"},"kind":"ClusterRoleBinding","tags":[],"namespace":"*","annotations":[{"key":"include.release.openshift.io/ibm-cloud-managed","value":"true"},{"key":"include.release.openshift.io/self-managed-high-availability","value":"true"},{"key":"include.release.openshift.io/single-node-developer","value":"true"}],"labels":[],"creationTime":1667113723,"id":"9374a9ee-c0eb-413f-a0cf-fbc9a2bb858a","type":"KubernetesRoleBinding","name":"default-account-cluster-network-operator","dome9Id":"11|5af13ab5-72ed-43b6-9544-33c9236d62f0|ClusterRoleBinding|9374a9ee-c0eb-413f-a0cf-fbc9a2bb858a","accountNumber":"5af13ab5-72ed-43b6-9544-33c9236d62f0","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_12/webhook-1686308573012.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"T3SuYYlUQge7Rl1e1n87TA","findingId":"T3SuYYlUQge7Rl1e1n87TA","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"CIS Kubernetes Benchmark v1.6.1","description":"Automated Validation of Kubernetes CIS Benchmark v1.6.1 Prescriptive guidance for establishing a secure configuration posture for Kubernetes 1.6.1\nFor additional reference: https://www.cisecurity.org/benchmark/kubernetes/","id":-70},"reportTime":"2023-06-09T11:00:31.243Z","rule":{"name":"Ensure that default service accounts are not actively used. (RBAC)","ruleId":"D9.K8S.IAM.36","description":"The default service account should not be used to ensure that rights granted to applications can be more easily audited and reviewed. Kubernetes provides a default service account which is used by cluster workloads where no specific service account is assigned to the pod. Where access to the Kubernetes API from a pod is required, a specific service account should be created for that pod, and rights granted to that service account. The default service account should be configured such that it does not provide a service account token and does not have any explicit rights assignments.","remediation":"Create explicit service accounts wherever a Kubernetes workload requires specific access to the Kubernetes API server. Modify the configuration of each default service account to include this value:\nautomountServiceAccountToken: false\n\n**References**\n1. https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/\n2. https://aws.github.io/aws-eks-best-practices/iam/#disable-auto-mounting-ofservice-account-tokens (EKS) ","complianceTags":"5.1.5","logicHash":"iyh0kLFb/m3DBPWpu8MYrg","severity":"Low"},"account":{"id":"5af13ab5-72ed-43b6-9544-33c9236d62f0","name":"nu-openshift-cluster","vendor":"Kubernetes","dome9CloudAccountId":"5af13ab5-72ed-43b6-9544-33c9236d62f0","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"subjects":[{"apiGroup":null,"kind":"ServiceAccount","name":"default","namespace":"openshift-marketplace"}],"role":{"name":"f066e085c03d92960c884f303e4204521793bc2bb167356ab83ab31fe3b713a","rules":[{"apiGroups":[""],"nonResourceURLs":null,"resourceNames":["f066e085c03d92960c884f303e4204521793bc2bb167356ab83ab31fe3b713a"],"resources":["configmaps"],"verbs":["create","get","update"]}],"aggregationRule":null,"kind":"Role"},"kind":"RoleBinding","tags":[],"namespace":"openshift-marketplace","annotations":[],"labels":[],"creationTime":1676406795,"id":"d2b76a2f-0f52-4abc-a8de-da09c4a83a6b","type":"KubernetesRoleBinding","name":"f066e085c03d92960c884f303e4204521793bc2bb167356ab83ab31fe3b713a","dome9Id":"11|5af13ab5-72ed-43b6-9544-33c9236d62f0|RoleBinding|d2b76a2f-0f52-4abc-a8de-da09c4a83a6b","accountNumber":"5af13ab5-72ed-43b6-9544-33c9236d62f0","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/webhook-1686308461848.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"6tOEUDyxzeKI2Ne4VOY/2Q","findingId":"6tOEUDyxzeKI2Ne4VOY/2Q","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"CIS Kubernetes Benchmark v1.6.1","description":"Automated Validation of Kubernetes CIS Benchmark v1.6.1 Prescriptive guidance for establishing a secure configuration posture for Kubernetes 1.6.1\nFor additional reference: https://www.cisecurity.org/benchmark/kubernetes/","id":-70},"reportTime":"2023-06-09T11:00:31.243Z","rule":{"name":"Minimize access to create pods (RBAC)","ruleId":"D9.K8S.IAM.35","description":"The ability to create pods in a namespace can provide a number of opportunities for privilege escalation, such as assigning privileged service accounts to these pods or mounting hostPaths with access to sensitive data (unless Pod Security Policies are implemented to restrict this access). As such, access to create new pods should be restricted to the smallest possible group of users. The ability to create pods in a cluster opens up possibilities for privilege escalation and should be restricted, where possible.","remediation":"Where possible, remove create access to pod objects in the cluster.","complianceTags":"5.1.4","logicHash":"grYFwC76VTIueiiCNKmvrw","severity":"Low"},"account":{"id":"5af13ab5-72ed-43b6-9544-33c9236d62f0","name":"nu-openshift-cluster","vendor":"Kubernetes","dome9CloudAccountId":"5af13ab5-72ed-43b6-9544-33c9236d62f0","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"subjects":[{"apiGroup":null,"kind":"ServiceAccount","name":"local-storage-admin","namespace":"storage"}],"role":{"name":"local-storage-operator.4.11.0-202304181642-local-sto-6c44964df7","rules":[{"apiGroups":["local.storage.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["*"],"verbs":["get","list","watch","create","update"]}],"aggregationRule":null,"kind":"Role"},"kind":"RoleBinding","tags":[{"key":"olm.owner","value":"local-storage-operator.4.11.0-202304181642"},{"key":"olm.owner.kind","value":"ClusterServiceVersion"},{"key":"olm.owner.namespace","value":"storage"},{"key":"operators.coreos.com/local-storage-operator.storage","value":""}],"namespace":"storage","annotations":[],"labels":[{"key":"olm.owner","value":"local-storage-operator.4.11.0-202304181642"},{"key":"olm.owner.kind","value":"ClusterServiceVersion"},{"key":"olm.owner.namespace","value":"storage"},{"key":"operators.coreos.com/local-storage-operator.storage","value":""}],"creationTime":1682468851,"id":"d810053e-c416-4f2a-a790-44a898591b39","type":"KubernetesRoleBinding","name":"local-storage-operator.4.11.0-202304181642-local-sto-6c44964df7","dome9Id":"11|5af13ab5-72ed-43b6-9544-33c9236d62f0|RoleBinding|d810053e-c416-4f2a-a790-44a898591b39","accountNumber":"5af13ab5-72ed-43b6-9544-33c9236d62f0","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_4/webhook-1686308476591.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"AwlYRrXF8juJOu3CULhvxw","findingId":"AwlYRrXF8juJOu3CULhvxw","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"CIS Kubernetes Benchmark v1.6.1","description":"Automated Validation of Kubernetes CIS Benchmark v1.6.1 Prescriptive guidance for establishing a secure configuration posture for Kubernetes 1.6.1\nFor additional reference: https://www.cisecurity.org/benchmark/kubernetes/","id":-70},"reportTime":"2023-06-09T11:00:31.243Z","rule":{"name":"Ensure that the cluster-admin role is only used where required (RBAC)","ruleId":"D9.K8S.IAM.32","description":"The RBAC role cluster-admin provides wide-ranging powers over the environment and should be used only where and when needed. Kubernetes provides a set of default roles where RBAC is used. Some of these roles such as cluster-admin provide wide-ranging privileges which should only be applied where absolutely necessary. Roles such as cluster-admin allow super-user access to perform any action on any resource. When used in a ClusterRoleBinding, it gives full control over every resource in the cluster and in all namespaces. When used in a RoleBinding, it gives full control over every resource in the rolebinding's namespace, including the namespace itself.","remediation":"Identify all clusterrolebindings to the cluster-admin role. Check if they are used and if they need this role or if they could use a role with fewer privileges. Where possible, first bind users to a lower privileged role and then remove the clusterrolebinding to the cluster-admin role :\nkubectl delete clusterrolebinding [name]\n\n**References**\n1. https://kubernetes.io/docs/admin/authorization/rbac/#user-facing-roles\n2. https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/ (EKS)","complianceTags":"5.1.1","logicHash":"3p9sRlFV3fSLPQfo9uR9ZQ","severity":"Informational"},"account":{"id":"5af13ab5-72ed-43b6-9544-33c9236d62f0","name":"nu-openshift-cluster","vendor":"Kubernetes","dome9CloudAccountId":"5af13ab5-72ed-43b6-9544-33c9236d62f0","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"subjects":[{"apiGroup":null,"kind":"ServiceAccount","name":"openshift-config-operator","namespace":"openshift-config-operator"}],"role":{"name":"cluster-admin","rules":[{"apiGroups":["*"],"nonResourceURLs":null,"resourceNames":null,"resources":["*"],"verbs":["*"]},{"apiGroups":null,"nonResourceURLs":["*"],"resourceNames":null,"resources":null,"verbs":["*"]}],"aggregationRule":null,"kind":"ClusterRole"},"kind":"ClusterRoleBinding","tags":[],"namespace":"*","annotations":[{"key":"include.release.openshift.io/ibm-cloud-managed","value":"true"},{"key":"include.release.openshift.io/self-managed-high-availability","value":"true"},{"key":"include.release.openshift.io/single-node-developer","value":"true"}],"labels":[],"creationTime":1667113733,"id":"e7daea09-cf15-4c60-8faf-cea9ff9f15da","type":"KubernetesRoleBinding","name":"system:openshift:operator:openshift-config-operator","dome9Id":"11|5af13ab5-72ed-43b6-9544-33c9236d62f0|ClusterRoleBinding|e7daea09-cf15-4c60-8faf-cea9ff9f15da","accountNumber":"5af13ab5-72ed-43b6-9544-33c9236d62f0","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/webhook-1686308559056.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"qCMOQVnELvLCI/WBHq3ioQ","findingId":"qCMOQVnELvLCI/WBHq3ioQ","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"CIS Kubernetes Benchmark v1.6.1","description":"Automated Validation of Kubernetes CIS Benchmark v1.6.1 Prescriptive guidance for establishing a secure configuration posture for Kubernetes 1.6.1\nFor additional reference: https://www.cisecurity.org/benchmark/kubernetes/","id":-70},"reportTime":"2023-06-09T11:00:31.243Z","rule":{"name":"Minimize access to create pods (RBAC)","ruleId":"D9.K8S.IAM.35","description":"The ability to create pods in a namespace can provide a number of opportunities for privilege escalation, such as assigning privileged service accounts to these pods or mounting hostPaths with access to sensitive data (unless Pod Security Policies are implemented to restrict this access). As such, access to create new pods should be restricted to the smallest possible group of users. The ability to create pods in a cluster opens up possibilities for privilege escalation and should be restricted, where possible.","remediation":"Where possible, remove create access to pod objects in the cluster.","complianceTags":"5.1.4","logicHash":"grYFwC76VTIueiiCNKmvrw","severity":"Low"},"account":{"id":"5af13ab5-72ed-43b6-9544-33c9236d62f0","name":"nu-openshift-cluster","vendor":"Kubernetes","dome9CloudAccountId":"5af13ab5-72ed-43b6-9544-33c9236d62f0","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"subjects":[{"apiGroup":null,"kind":"ServiceAccount","name":"machine-api-controllers","namespace":"openshift-machine-api"}],"role":{"name":"machine-api-controllers","rules":[{"apiGroups":["machine.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["*"],"verbs":["*"]},{"apiGroups":["healthchecking.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["*"],"verbs":["*"]},{"apiGroups":[""],"nonResourceURLs":null,"resourceNames":null,"resources":["configmaps"],"verbs":["get","list","watch","create","update","patch","delete"]},{"apiGroups":[""],"nonResourceURLs":null,"resourceNames":null,"resources":["secrets"],"verbs":["get","list","watch","create","update","patch","delete"]},{"apiGroups":["coordination.k8s.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["leases"],"verbs":["get","list","watch","create","update","patch","delete"]},{"apiGroups":[""],"nonResourceURLs":null,"resourceNames":null,"resources":["events"],"verbs":["create","watch","list","patch"]},{"apiGroups":["metal3.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["baremetalhosts"],"verbs":["get","list","watch","update","patch"]},{"apiGroups":["metal3.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["baremetalhosts/status","baremetalhosts/finalizers"],"verbs":["update"]}],"aggregationRule":null,"kind":"Role"},"kind":"RoleBinding","tags":[],"namespace":"openshift-machine-api","annotations":[{"key":"include.release.openshift.io/self-managed-high-availability","value":"true"},{"key":"include.release.openshift.io/single-node-developer","value":"true"}],"labels":[],"creationTime":1667113755,"id":"cfee62dc-7699-4490-b84b-893cb543857e","type":"KubernetesRoleBinding","name":"machine-api-controllers","dome9Id":"11|5af13ab5-72ed-43b6-9544-33c9236d62f0|RoleBinding|cfee62dc-7699-4490-b84b-893cb543857e","accountNumber":"5af13ab5-72ed-43b6-9544-33c9236d62f0","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/webhook-1686308466956.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"/8JcT1at9PWIykouwAxjYQ","findingId":"/8JcT1at9PWIykouwAxjYQ","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"CIS Kubernetes Benchmark v1.6.1","description":"Automated Validation of Kubernetes CIS Benchmark v1.6.1 Prescriptive guidance for establishing a secure configuration posture for Kubernetes 1.6.1\nFor additional reference: https://www.cisecurity.org/benchmark/kubernetes/","id":-70},"reportTime":"2023-06-09T11:00:31.243Z","rule":{"name":"Minimize access to create pods (RBAC)","ruleId":"D9.K8S.IAM.35","description":"The ability to create pods in a namespace can provide a number of opportunities for privilege escalation, such as assigning privileged service accounts to these pods or mounting hostPaths with access to sensitive data (unless Pod Security Policies are implemented to restrict this access). As such, access to create new pods should be restricted to the smallest possible group of users. The ability to create pods in a cluster opens up possibilities for privilege escalation and should be restricted, where possible.","remediation":"Where possible, remove create access to pod objects in the cluster.","complianceTags":"5.1.4","logicHash":"grYFwC76VTIueiiCNKmvrw","severity":"Low"},"account":{"id":"5af13ab5-72ed-43b6-9544-33c9236d62f0","name":"nu-openshift-cluster","vendor":"Kubernetes","dome9CloudAccountId":"5af13ab5-72ed-43b6-9544-33c9236d62f0","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"subjects":[{"apiGroup":null,"kind":"ServiceAccount","name":"openshift-apiserver-sa","namespace":"openshift-apiserver"}],"role":{"name":"cluster-admin","rules":[{"apiGroups":["*"],"nonResourceURLs":null,"resourceNames":null,"resources":["*"],"verbs":["*"]},{"apiGroups":null,"nonResourceURLs":["*"],"resourceNames":null,"resources":null,"verbs":["*"]}],"aggregationRule":null,"kind":"ClusterRole"},"kind":"ClusterRoleBinding","tags":[],"namespace":"*","annotations":[],"labels":[],"creationTime":1667113863,"id":"a3daded0-2567-4bf6-b175-595f50ac49c1","type":"KubernetesRoleBinding","name":"system:openshift:openshift-apiserver","dome9Id":"11|5af13ab5-72ed-43b6-9544-33c9236d62f0|ClusterRoleBinding|a3daded0-2567-4bf6-b175-595f50ac49c1","accountNumber":"5af13ab5-72ed-43b6-9544-33c9236d62f0","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}
