=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_7/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "status": {
            "type": "string"
        },
        "policy": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "description",
                "name"
            ]
        },
        "findingKey": {
            "type": "string"
        },
        "findingId": {
            "type": "string"
        },
        "cloudGuardAccountId": {
            "type": "string"
        },
        "origin": {
            "type": "string"
        },
        "bundle": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            },
            "required": [
                "description",
                "id",
                "name"
            ]
        },
        "reportTime": {
            "type": "string"
        },
        "rule": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "ruleId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "remediation": {
                    "type": "string"
                },
                "complianceTags": {
                    "type": "string"
                },
                "logicHash": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                }
            },
            "required": [
                "complianceTags",
                "description",
                "logicHash",
                "name",
                "remediation",
                "ruleId",
                "severity"
            ]
        },
        "account": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                },
                "dome9CloudAccountId": {
                    "type": "string"
                },
                "organizationalUnitId": {
                    "type": "string"
                },
                "organizationalUnitPath": {
                    "type": "string"
                }
            },
            "required": [
                "dome9CloudAccountId",
                "id",
                "name",
                "organizationalUnitId",
                "organizationalUnitPath",
                "vendor"
            ]
        },
        "region": {
            "type": "string"
        },
        "entity": {
            "type": "object",
            "properties": {
                "acl": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "bucket": {
                                "type": "string"
                            },
                            "domain": {
                                "type": "null"
                            },
                            "email": {
                                "type": "null"
                            },
                            "entity": {
                                "type": "string"
                            },
                            "entityId": {
                                "type": "null"
                            },
                            "eTag": {
                                "type": "null"
                            },
                            "generation": {
                                "type": "null"
                            },
                            "id": {
                                "type": "string"
                            },
                            "kind": {
                                "type": "string"
                            },
                            "object__": {
                                "type": "null"
                            },
                            "projectTeam": {
                                "type": "object",
                                "properties": {
                                    "projectNumber": {
                                        "type": "string"
                                    },
                                    "team": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "projectNumber",
                                    "team"
                                ]
                            },
                            "role": {
                                "type": "string"
                            },
                            "selfLink": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "bucket",
                            "domain",
                            "eTag",
                            "email",
                            "entity",
                            "entityId",
                            "generation",
                            "id",
                            "kind",
                            "object__",
                            "projectTeam",
                            "role",
                            "selfLink"
                        ]
                    }
                },
                "defaultObjectAcl": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "bucket": {
                                "type": "null"
                            },
                            "domain": {
                                "type": "null"
                            },
                            "email": {
                                "type": "null"
                            },
                            "entity": {
                                "type": "string"
                            },
                            "entityId": {
                                "type": "null"
                            },
                            "eTag": {
                                "type": "null"
                            },
                            "generation": {
                                "type": "null"
                            },
                            "id": {
                                "type": "null"
                            },
                            "kind": {
                                "type": "string"
                            },
                            "object__": {
                                "type": "null"
                            },
                            "projectTeam": {
                                "type": "object",
                                "properties": {
                                    "projectNumber": {
                                        "type": "string"
                                    },
                                    "team": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "projectNumber",
                                    "team"
                                ]
                            },
                            "role": {
                                "type": "string"
                            },
                            "selfLink": {
                                "type": "null"
                            }
                        },
                        "required": [
                            "bucket",
                            "domain",
                            "eTag",
                            "email",
                            "entity",
                            "entityId",
                            "generation",
                            "id",
                            "kind",
                            "object__",
                            "projectTeam",
                            "role",
                            "selfLink"
                        ]
                    }
                },
                "location": {
                    "type": "string"
                },
                "logging": {
                    "type": "null"
                },
                "metageneration": {
                    "type": "integer"
                },
                "owner": {
                    "type": "object",
                    "properties": {
                        "entity": {
                            "type": "string"
                        },
                        "entityId": {
                            "type": "null"
                        }
                    },
                    "required": [
                        "entity",
                        "entityId"
                    ]
                },
                "projectNumber": {
                    "type": "integer"
                },
                "storageClass": {
                    "type": "string"
                },
                "timeCreatedRaw": {
                    "type": "string"
                },
                "timeCreated": {
                    "type": "integer"
                },
                "updatedRaw": {
                    "type": "string"
                },
                "updated": {
                    "type": "integer"
                },
                "iamPolicy": {
                    "type": "object",
                    "properties": {
                        "bindings": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "members": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    },
                                    "role": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "members",
                                    "role"
                                ]
                            }
                        },
                        "eTag": {
                            "type": "string"
                        },
                        "kind": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "bindings",
                        "eTag",
                        "kind"
                    ]
                },
                "defaultEventBasedHold": {
                    "type": "null"
                },
                "iamConfiguration": {
                    "type": "object",
                    "properties": {
                        "bucketPolicyOnly": {
                            "type": "object",
                            "properties": {
                                "enabled": {
                                    "type": "boolean"
                                },
                                "lockedTimeRaw": {
                                    "type": "null"
                                },
                                "lockedTime": {
                                    "type": "null"
                                }
                            },
                            "required": [
                                "enabled",
                                "lockedTime",
                                "lockedTimeRaw"
                            ]
                        },
                        "uniformBucketLevelAccess": {
                            "type": "object",
                            "properties": {
                                "enabled": {
                                    "type": "boolean"
                                },
                                "lockedTimeRaw": {
                                    "type": "null"
                                },
                                "lockedTime": {
                                    "type": "null"
                                }
                            },
                            "required": [
                                "enabled",
                                "lockedTime",
                                "lockedTimeRaw"
                            ]
                        },
                        "publicAccessPrevention": {
                            "type": "null"
                        }
                    },
                    "required": [
                        "bucketPolicyOnly",
                        "publicAccessPrevention",
                        "uniformBucketLevelAccess"
                    ]
                },
                "retentionPolicy": {
                    "type": "null"
                },
                "locationType": {
                    "type": "null"
                },
                "customPlacementConfig": {
                    "type": "null"
                },
                "satisfiesPZS": {
                    "type": "null"
                },
                "rpo": {
                    "type": "null"
                },
                "selfLink": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "dome9Id": {
                    "type": "string"
                },
                "accountNumber": {
                    "type": "string"
                },
                "assetLabels": {
                    "type": "null"
                },
                "region": {
                    "type": "string"
                },
                "externalFindings": {
                    "type": "null"
                }
            },
            "required": [
                "accountNumber",
                "acl",
                "assetLabels",
                "customPlacementConfig",
                "defaultEventBasedHold",
                "defaultObjectAcl",
                "dome9Id",
                "externalFindings",
                "iamConfiguration",
                "iamPolicy",
                "id",
                "location",
                "locationType",
                "logging",
                "metageneration",
                "name",
                "owner",
                "projectNumber",
                "region",
                "retentionPolicy",
                "rpo",
                "satisfiesPZS",
                "selfLink",
                "storageClass",
                "timeCreated",
                "timeCreatedRaw",
                "type",
                "updated",
                "updatedRaw"
            ]
        },
        "remediationActions": {
            "type": "array"
        },
        "action": {
            "type": "string"
        },
        "additionalFields": {
            "type": "array"
        }
    },
    "required": [
        "account",
        "action",
        "additionalFields",
        "bundle",
        "cloudGuardAccountId",
        "entity",
        "findingId",
        "findingKey",
        "origin",
        "policy",
        "region",
        "remediationActions",
        "reportTime",
        "rule",
        "status"
    ]
}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/webhook-1686305248693.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"ihj584/Qg/lm+Pow+hoAsQ","findingId":"ihj584/Qg/lm+Pow+hoAsQ","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"GCP CloudGuard Best Practices","description":"CloudGuard Best Practices for securing GCP Account","id":-9},"reportTime":"2023-06-09T10:06:38.111Z","rule":{"name":"Ensure that Cloud Storage bucket has usage logs enabled","ruleId":"D9.GCP.LOG.01","description":"Turn on usage logs on your Storage Bucket in order to log access of users to public resources, and follow changes with to Object Lifecycle Management feature. Other actions are logged with Cloud Audit Logs, which has to be enabled as well.","remediation":"\n**From Command Line**\nIn order to enable usage logs you should:\n1. Create a bucket to store the logs:\n```\ngsutil mb gs://Bucket_for_logs_storing\n```\n2. Grant it with 'roles/storage.legacyBucketWriter' permissions:\n```\ngsutil iam ch group:cloud-storage-analytics@google.com:legacyBucketWriter gs://<Bucket for logs storing>\n```\n3. Enable usage logging to your desired logs:\n```\ngsutil logging set on -b gs://<Bucket for logs storing> gs://<Bucket to log>\n```\n\n**References**\n1. https://cloud.google.com/storage/docs/gsutil/commands/mb\n2. https://cloud.google.com/storage/docs/gsutil/commands/iam\n3. https://cloud.google.com/storage/docs/gsutil/commands/logging\n4. https://cloud.google.com/storage/docs/access-logs","complianceTags":"Logging","logicHash":"zc2ibp/ZUCkzWPBR5tUhkg","severity":"Low"},"account":{"id":"serious-conduit-389105","name":"GCP Demo Account NU","vendor":"GCP","dome9CloudAccountId":"ca5ef528-d8dd-41d8-a022-1a820a6adb60","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"US","entity":{"acl":[{"bucket":"nilsujma-wh","domain":null,"email":null,"entity":"project-owners-554880214893","entityId":null,"eTag":null,"generation":null,"id":"nilsujma-wh/project-owners-554880214893","kind":"storage#bucketAccessControl","object__":null,"projectTeam":{"projectNumber":"554880214893","team":"owners"},"role":"OWNER","selfLink":"https://www.googleapis.com/storage/v1/b/nilsujma-wh/acl/project-owners-554880214893"},{"bucket":"nilsujma-wh","domain":null,"email":null,"entity":"project-editors-554880214893","entityId":null,"eTag":null,"generation":null,"id":"nilsujma-wh/project-editors-554880214893","kind":"storage#bucketAccessControl","object__":null,"projectTeam":{"projectNumber":"554880214893","team":"editors"},"role":"OWNER","selfLink":"https://www.googleapis.com/storage/v1/b/nilsujma-wh/acl/project-editors-554880214893"},{"bucket":"nilsujma-wh","domain":null,"email":null,"entity":"project-viewers-554880214893","entityId":null,"eTag":null,"generation":null,"id":"nilsujma-wh/project-viewers-554880214893","kind":"storage#bucketAccessControl","object__":null,"projectTeam":{"projectNumber":"554880214893","team":"viewers"},"role":"READER","selfLink":"https://www.googleapis.com/storage/v1/b/nilsujma-wh/acl/project-viewers-554880214893"}],"defaultObjectAcl":[{"bucket":null,"domain":null,"email":null,"entity":"project-owners-554880214893","entityId":null,"eTag":null,"generation":null,"id":null,"kind":"storage#objectAccessControl","object__":null,"projectTeam":{"projectNumber":"554880214893","team":"owners"},"role":"OWNER","selfLink":null},{"bucket":null,"domain":null,"email":null,"entity":"project-editors-554880214893","entityId":null,"eTag":null,"generation":null,"id":null,"kind":"storage#objectAccessControl","object__":null,"projectTeam":{"projectNumber":"554880214893","team":"editors"},"role":"OWNER","selfLink":null},{"bucket":null,"domain":null,"email":null,"entity":"project-viewers-554880214893","entityId":null,"eTag":null,"generation":null,"id":null,"kind":"storage#objectAccessControl","object__":null,"projectTeam":{"projectNumber":"554880214893","team":"viewers"},"role":"READER","selfLink":null}],"location":"US","logging":null,"metageneration":1,"owner":{"entity":"project-owners-554880214893","entityId":null},"projectNumber":554880214893,"storageClass":"STANDARD","timeCreatedRaw":"2023-06-09T09:51:07.535Z","timeCreated":1686304267,"updatedRaw":"2023-06-09T09:51:07.535Z","updated":1686304267,"iamPolicy":{"bindings":[{"members":["projectEditor:serious-conduit-389105","projectOwner:serious-conduit-389105"],"role":"roles/storage.legacyBucketOwner"},{"members":["projectViewer:serious-conduit-389105"],"role":"roles/storage.legacyBucketReader"}],"eTag":"CAE=","kind":"storage#policy"},"defaultEventBasedHold":null,"iamConfiguration":{"bucketPolicyOnly":{"enabled":false,"lockedTimeRaw":null,"lockedTime":null},"uniformBucketLevelAccess":{"enabled":false,"lockedTimeRaw":null,"lockedTime":null},"publicAccessPrevention":null},"retentionPolicy":null,"locationType":null,"customPlacementConfig":null,"satisfiesPZS":null,"rpo":null,"selfLink":"https://www.googleapis.com/storage/v1/b/nilsujma-wh","id":"nilsujma-wh","type":"StorageBucket","name":"nilsujma-wh","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|StorageBucket|nilsujma-wh","accountNumber":"serious-conduit-389105","assetLabels":null,"region":"US","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/webhook-1686305248311.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"LrG+0KUrJykLlxRQy5eUPQ","findingId":"LrG+0KUrJykLlxRQy5eUPQ","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"GCP CloudGuard Best Practices","description":"CloudGuard Best Practices for securing GCP Account","id":-9},"reportTime":"2023-06-09T10:06:38.111Z","rule":{"name":"Ensure that Cloud Storage buckets have uniform bucket-level access enabled","ruleId":"D9.GCP.IAM.27","description":"It is recommended that uniform bucket-level access is enabled on Cloud Storage buckets.\nIt is recommended to use uniform bucket-level access to unify and simplify how you grant access to your Cloud Storage resources.\nCloud Storage offers two systems for granting users permission to access your buckets and objects: Cloud Identity and Access Management (Cloud IAM) and Access Control Lists (ACLs). These systems act in parallel - in order for a user to access a Cloud Storage resource, only one of the systems needs to grant the user permission. Cloud IAM is used throughout Google Cloud and allows you to grant a variety of permissions at the bucket and project levels. ACLs are used only by Cloud Storage and have limited permission options, but they allow you to grant permissions on a per-object basis.\nIn order to support a uniform permissioning system, Cloud Storage has uniform bucket-level access. Using this feature disables ACLs for all Cloud Storage resources: access to Cloud Storage resources then is granted exclusively through Cloud IAM. Enabling uniform bucket-level access guarantees that if a Storage bucket is not publicly accessible, no object in the bucket is publicly accessible either.\nIf you enable uniform bucket-level access, you revoke access from users who gain their access solely through object ACLs.\nCertain Google Cloud services, such as Stackdriver, Cloud Audit Logs, and Datastore, cannot export to Cloud Storage buckets that have uniform bucket-level access enabled.","remediation":"\n**From Portal**\n1. Open the Cloud Storage browser in the Google Cloud Console by visiting: https://console.cloud.google.com/storage/browser\n2. In the list of buckets, click on the name of the desired bucket.\n3. Select the Permissions tab near the top of the page.\n4. In the text box named Access Control, click the Switch to link. Note that the text box disappears 90 days after you enable uniform bucket-level access.\n5. In the pop-up menu that appears, select Uniform or Fine-grained.\n6. Click Save\n\n**From Command Line**\n1. To list all buckets in a project\n```\ngsutil ls\n```\n2. Use the 'on' option in a uniformbucketlevelaccess set command:\n```\ngsutil uniformbucketlevelaccess set on gs://BUCKET_NAME/\n```\n\n**From Terraform**\nUse Resource: google_storage_bucket and  Argument: uniform_bucket_level_access is set to true,\n```\nresource \"google_storage_bucket\" \"My-bucket\" {\nproject       = \"PROJECT_ID\"\nname          = \"BUCKET_NAME\"\nlocation      = \"CHOOSE_REGION\"\n\nuniform_bucket_level_access = true\n}\n```\n\n**References**\n1. https://cloud.google.com/storage/docs/uniform-bucket-level-access\n2. https://cloud.google.com/storage/docs/using-uniform-bucket-level-access\n3. https://cloud.google.com/storage/docs/setting-org-policies#uniform-bucket\n4. https://workbench.cisecurity.org/sections/507173/recommendations/827577 ","complianceTags":"Identity and Access Management","logicHash":"9I9FFkFbA6x7Ct5LcjTUXw","severity":"Low"},"account":{"id":"serious-conduit-389105","name":"GCP Demo Account NU","vendor":"GCP","dome9CloudAccountId":"ca5ef528-d8dd-41d8-a022-1a820a6adb60","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"US","entity":{"acl":[{"bucket":"nilsujma-wh","domain":null,"email":null,"entity":"project-owners-554880214893","entityId":null,"eTag":null,"generation":null,"id":"nilsujma-wh/project-owners-554880214893","kind":"storage#bucketAccessControl","object__":null,"projectTeam":{"projectNumber":"554880214893","team":"owners"},"role":"OWNER","selfLink":"https://www.googleapis.com/storage/v1/b/nilsujma-wh/acl/project-owners-554880214893"},{"bucket":"nilsujma-wh","domain":null,"email":null,"entity":"project-editors-554880214893","entityId":null,"eTag":null,"generation":null,"id":"nilsujma-wh/project-editors-554880214893","kind":"storage#bucketAccessControl","object__":null,"projectTeam":{"projectNumber":"554880214893","team":"editors"},"role":"OWNER","selfLink":"https://www.googleapis.com/storage/v1/b/nilsujma-wh/acl/project-editors-554880214893"},{"bucket":"nilsujma-wh","domain":null,"email":null,"entity":"project-viewers-554880214893","entityId":null,"eTag":null,"generation":null,"id":"nilsujma-wh/project-viewers-554880214893","kind":"storage#bucketAccessControl","object__":null,"projectTeam":{"projectNumber":"554880214893","team":"viewers"},"role":"READER","selfLink":"https://www.googleapis.com/storage/v1/b/nilsujma-wh/acl/project-viewers-554880214893"}],"defaultObjectAcl":[{"bucket":null,"domain":null,"email":null,"entity":"project-owners-554880214893","entityId":null,"eTag":null,"generation":null,"id":null,"kind":"storage#objectAccessControl","object__":null,"projectTeam":{"projectNumber":"554880214893","team":"owners"},"role":"OWNER","selfLink":null},{"bucket":null,"domain":null,"email":null,"entity":"project-editors-554880214893","entityId":null,"eTag":null,"generation":null,"id":null,"kind":"storage#objectAccessControl","object__":null,"projectTeam":{"projectNumber":"554880214893","team":"editors"},"role":"OWNER","selfLink":null},{"bucket":null,"domain":null,"email":null,"entity":"project-viewers-554880214893","entityId":null,"eTag":null,"generation":null,"id":null,"kind":"storage#objectAccessControl","object__":null,"projectTeam":{"projectNumber":"554880214893","team":"viewers"},"role":"READER","selfLink":null}],"location":"US","logging":null,"metageneration":1,"owner":{"entity":"project-owners-554880214893","entityId":null},"projectNumber":554880214893,"storageClass":"STANDARD","timeCreatedRaw":"2023-06-09T09:51:07.535Z","timeCreated":1686304267,"updatedRaw":"2023-06-09T09:51:07.535Z","updated":1686304267,"iamPolicy":{"bindings":[{"members":["projectEditor:serious-conduit-389105","projectOwner:serious-conduit-389105"],"role":"roles/storage.legacyBucketOwner"},{"members":["projectViewer:serious-conduit-389105"],"role":"roles/storage.legacyBucketReader"}],"eTag":"CAE=","kind":"storage#policy"},"defaultEventBasedHold":null,"iamConfiguration":{"bucketPolicyOnly":{"enabled":false,"lockedTimeRaw":null,"lockedTime":null},"uniformBucketLevelAccess":{"enabled":false,"lockedTimeRaw":null,"lockedTime":null},"publicAccessPrevention":null},"retentionPolicy":null,"locationType":null,"customPlacementConfig":null,"satisfiesPZS":null,"rpo":null,"selfLink":"https://www.googleapis.com/storage/v1/b/nilsujma-wh","id":"nilsujma-wh","type":"StorageBucket","name":"nilsujma-wh","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|StorageBucket|nilsujma-wh","accountNumber":"serious-conduit-389105","assetLabels":null,"region":"US","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}
