=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_46/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "status": {
            "type": "string"
        },
        "policy": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "description",
                "name"
            ]
        },
        "findingKey": {
            "type": "string"
        },
        "findingId": {
            "type": "string"
        },
        "cloudGuardAccountId": {
            "type": "string"
        },
        "origin": {
            "type": "string"
        },
        "bundle": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            },
            "required": [
                "description",
                "id",
                "name"
            ]
        },
        "reportTime": {
            "type": "string"
        },
        "rule": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "ruleId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "remediation": {
                    "type": "string"
                },
                "complianceTags": {
                    "type": "string"
                },
                "logicHash": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                }
            },
            "required": [
                "complianceTags",
                "description",
                "logicHash",
                "name",
                "remediation",
                "ruleId",
                "severity"
            ]
        },
        "account": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                },
                "dome9CloudAccountId": {
                    "type": "string"
                },
                "organizationalUnitId": {
                    "type": "string"
                },
                "organizationalUnitPath": {
                    "type": "string"
                }
            },
            "required": [
                "dome9CloudAccountId",
                "id",
                "name",
                "organizationalUnitId",
                "organizationalUnitPath",
                "vendor"
            ]
        },
        "region": {
            "type": "string"
        },
        "entity": {
            "type": "object",
            "properties": {
                "user": {
                    "type": "string"
                },
                "roleNames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "auditConfigsExemption": {
                    "type": "null"
                },
                "userData": {
                    "type": "null"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "deleted": {
                                "type": "null"
                            },
                            "description": {
                                "type": "string"
                            },
                            "eTag": {
                                "type": "string"
                            },
                            "stage": {
                                "type": "string"
                            },
                            "title": {
                                "type": "string"
                            },
                            "selfLink": {
                                "type": "null"
                            },
                            "id": {
                                "type": "string"
                            },
                            "type": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string"
                            },
                            "dome9Id": {
                                "type": "string"
                            },
                            "accountNumber": {
                                "type": "string"
                            },
                            "assetLabels": {
                                "type": "null"
                            },
                            "region": {
                                "type": "string"
                            },
                            "externalFindings": {
                                "type": "null"
                            }
                        },
                        "required": [
                            "accountNumber",
                            "assetLabels",
                            "deleted",
                            "description",
                            "dome9Id",
                            "eTag",
                            "externalFindings",
                            "id",
                            "name",
                            "region",
                            "selfLink",
                            "stage",
                            "title",
                            "type"
                        ]
                    }
                },
                "selfLink": {
                    "type": "null"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "dome9Id": {
                    "type": "string"
                },
                "accountNumber": {
                    "type": "string"
                },
                "assetLabels": {
                    "type": "null"
                },
                "region": {
                    "type": "string"
                },
                "externalFindings": {
                    "type": "null"
                }
            },
            "required": [
                "accountNumber",
                "assetLabels",
                "auditConfigsExemption",
                "dome9Id",
                "externalFindings",
                "id",
                "name",
                "region",
                "roleNames",
                "roles",
                "selfLink",
                "type",
                "user",
                "userData"
            ]
        },
        "remediationActions": {
            "type": "array"
        },
        "action": {
            "type": "string"
        },
        "additionalFields": {
            "type": "array"
        }
    },
    "required": [
        "account",
        "action",
        "additionalFields",
        "bundle",
        "cloudGuardAccountId",
        "entity",
        "findingId",
        "findingKey",
        "origin",
        "policy",
        "region",
        "remediationActions",
        "reportTime",
        "rule",
        "status"
    ]
}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/webhook-1686305221827.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"E4U6SBw2X1cnuxtTX2XTUw","findingId":"E4U6SBw2X1cnuxtTX2XTUw","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"GCP CloudGuard Best Practices","description":"CloudGuard Best Practices for securing GCP Account","id":-9},"reportTime":"2023-06-09T09:04:54.86Z","rule":{"name":"Ensure that multi-factor authentication is enabled for all non-service accounts","ruleId":"D9.GCP.IAM.03","description":"Setup multi-factor authentication for Google Cloud Platform accounts. Multi-factor authentication requires more than one mechanism to authenticate a user. This secures your logins from attackers exploiting stolen or weak credentials.","remediation":"\n**From Portal**\n1. Go to Cloud Identity and Access Management (IAM) dashboard at https://console.cloud.google.com/iam-admin/iam.\n2. Choose the PERMISSIONS tab, then select View by PRINCIPALS\n3. Copy the email address of the user account that you want to examine\n4. Go to Google Account console at https://myaccount.google.com and sign in using the email address copied at the previous step to access the appropriate user account.\n5. In the navigation bar, select Security.\n6. On the Security page, in the Signing in to Google section, check 2-Step Verification configuration setting status. set the status to On.\n7. Repeat steps no. 3 - 6 for each user account that you want to examine, created for the selected GCP project.\n\n\nNote: if the role fails because the IAMUser userData is null -\n1. It might be because you didn't connect your Google Workspace (G-Suite) account to CloudGuard.\nThis can be done through CloudGuard console -> Assets -> Environments -> <Your GCP Project> -> Add GSuite\n2. The IAMUser is not part of your organization - which is not recommended, and probably should be removed from your GCP.\n\n**References**\n1. Guide for users to enable MFA: https://support.google.com/accounts/answer/185839\n2. https://cloud.google.com/identity/solutions/enforce-mfa\n3. https://support.google.com/a/answer/9176657\n","complianceTags":"Identity and Access Management","logicHash":"IZ+YSVILn2LM2FIwhTcV5Q","severity":"High"},"account":{"id":"serious-conduit-389105","name":"GCP Demo Account NU","vendor":"GCP","dome9CloudAccountId":"ca5ef528-d8dd-41d8-a022-1a820a6adb60","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"user":"user:nils@nilsujma.io","roleNames":["roles/owner"],"auditConfigsExemption":null,"userData":null,"roles":[{"deleted":null,"description":"Full access to most Google Cloud resources. See the list of included permissions.","eTag":"AA==","stage":"GA","title":"Owner","selfLink":null,"id":"roles/owner","type":"GcpIamRole","name":"Owner","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|GcpIamPredefinedRole|roles/owner","accountNumber":"serious-conduit-389105","assetLabels":null,"region":"Global","externalFindings":null}],"selfLink":null,"id":"IAM-USER-user:nils@nilsujma.io","type":"GcpIamUser","name":"user:nils@nilsujma.io","dome9Id":"","accountNumber":"serious-conduit-389105","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/webhook-1686305231492.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"mB7T/SH5pVeDu+JiqVMobw","findingId":"mB7T/SH5pVeDu+JiqVMobw","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"GCP CloudGuard Best Practices","description":"CloudGuard Best Practices for securing GCP Account","id":-9},"reportTime":"2023-06-09T09:04:54.86Z","rule":{"name":"User did not log in the past 90 days","ruleId":"D9.GCP.IAM.19","description":"It is recommended that all user accounts that have been unused for 90 days or more be removed or deactivated. Suspending or removing unused user accounts will reduce the window of opportunity for credentials associated with a compromised or abandoned account to be used.","remediation":"\n**From Portal**\n1. Go to Admin console : https://admin.google.com\n2. From the Admin console Home page, go to Users.\n3. In the Users list, find the user.\n4. Point to the user you want to delete and click Moreand thenDelete user\n5. Depending on your privileges as an admin, choose an option:\n- Delegated admins : To confirm that you understand the impact of deleting the account, check the boxes.\nor\n- Super admins: To transfer ownership of user content:\nIf you don't want to transfer the user's data, next to Data in other apps, select Don't transfer data.\nIf you do want to transfer the user's data:\na. Next to Data in other apps, select Transfer.\nb. In the Search for a user field, enter the name or email address of the user to whom you want to transfer the files deleted users files.\nc. Under Select data to transfer, check the boxes next to each option you want.\n6. Click Delete User.\n\n**References**\n1. https://support.google.com/a/answer/33314\n2. https://support.google.com/a/answer/33312\n","complianceTags":"Identity and Access Management","logicHash":"IlDIcugEbNjVKX+maYkClA","severity":"High"},"account":{"id":"serious-conduit-389105","name":"GCP Demo Account NU","vendor":"GCP","dome9CloudAccountId":"ca5ef528-d8dd-41d8-a022-1a820a6adb60","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"user":"user:nils@nilsujma.io","roleNames":["roles/owner"],"auditConfigsExemption":null,"userData":null,"roles":[{"deleted":null,"description":"Full access to most Google Cloud resources. See the list of included permissions.","eTag":"AA==","stage":"GA","title":"Owner","selfLink":null,"id":"roles/owner","type":"GcpIamRole","name":"Owner","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|GcpIamPredefinedRole|roles/owner","accountNumber":"serious-conduit-389105","assetLabels":null,"region":"Global","externalFindings":null}],"selfLink":null,"id":"IAM-USER-user:nils@nilsujma.io","type":"GcpIamUser","name":"user:nils@nilsujma.io","dome9Id":"","accountNumber":"serious-conduit-389105","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}
