=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_37/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "status": {
            "type": "string"
        },
        "policy": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "description",
                "name"
            ]
        },
        "findingKey": {
            "type": "string"
        },
        "findingId": {
            "type": "string"
        },
        "cloudGuardAccountId": {
            "type": "string"
        },
        "origin": {
            "type": "string"
        },
        "bundle": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            },
            "required": [
                "description",
                "id",
                "name"
            ]
        },
        "reportTime": {
            "type": "string"
        },
        "rule": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "ruleId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "remediation": {
                    "type": "string"
                },
                "complianceTags": {
                    "type": "string"
                },
                "logicHash": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                }
            },
            "required": [
                "complianceTags",
                "description",
                "logicHash",
                "name",
                "remediation",
                "ruleId",
                "severity"
            ]
        },
        "account": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                },
                "dome9CloudAccountId": {
                    "type": "string"
                },
                "organizationalUnitId": {
                    "type": "string"
                },
                "organizationalUnitPath": {
                    "type": "string"
                }
            },
            "required": [
                "dome9CloudAccountId",
                "id",
                "name",
                "organizationalUnitId",
                "organizationalUnitPath",
                "vendor"
            ]
        },
        "region": {
            "type": "string"
        },
        "entity": {
            "type": "object",
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "oauth2ClientId": {
                    "type": "string"
                },
                "projectId": {
                    "type": "string"
                },
                "uniqueId": {
                    "type": "string"
                },
                "keys": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "keyAlgorithm": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string"
                            },
                            "privateKeyData": {
                                "type": "null"
                            },
                            "privateKeyType": {
                                "type": "null"
                            },
                            "publicKeyData": {
                                "type": "null"
                            },
                            "validAfterTime": {
                                "type": "integer"
                            },
                            "validBeforeTime": {
                                "type": "integer"
                            },
                            "eTag": {
                                "type": "null"
                            },
                            "managedBy": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "eTag",
                            "keyAlgorithm",
                            "managedBy",
                            "name",
                            "privateKeyData",
                            "privateKeyType",
                            "publicKeyData",
                            "validAfterTime",
                            "validBeforeTime"
                        ]
                    }
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "auditConfigsExemption": {
                    "type": "null"
                },
                "selfLink": {
                    "type": "null"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "dome9Id": {
                    "type": "string"
                },
                "accountNumber": {
                    "type": "string"
                },
                "assetLabels": {
                    "type": "null"
                },
                "region": {
                    "type": "string"
                },
                "externalFindings": {
                    "type": "null"
                }
            },
            "required": [
                "accountNumber",
                "assetLabels",
                "auditConfigsExemption",
                "displayName",
                "dome9Id",
                "email",
                "externalFindings",
                "id",
                "keys",
                "name",
                "oauth2ClientId",
                "projectId",
                "region",
                "roles",
                "selfLink",
                "type",
                "uniqueId"
            ]
        },
        "remediationActions": {
            "type": "array"
        },
        "action": {
            "type": "string"
        },
        "additionalFields": {
            "type": "array"
        }
    },
    "required": [
        "account",
        "action",
        "additionalFields",
        "bundle",
        "cloudGuardAccountId",
        "entity",
        "findingId",
        "findingKey",
        "origin",
        "policy",
        "region",
        "remediationActions",
        "reportTime",
        "rule",
        "status"
    ]
}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/webhook-1686305207672.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"0q25yaKk/fxn/zjqVHtjyw","findingId":"0q25yaKk/fxn/zjqVHtjyw","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"GCP CloudGuard Best Practices","description":"CloudGuard Best Practices for securing GCP Account","id":-9},"reportTime":"2023-06-09T09:04:54.86Z","rule":{"name":"Ensure that there are only GCP-managed service account keys for each service account","ruleId":"D9.GCP.IAM.04","description":"Managing your own service account keys will result higher change for key exposure. You should avoid using user managed keys.","remediation":"\n**From Portal**\n1. Go to the IAM page in the GCP Console using https://console.cloud.google.com/iam-admin/iam\n2. In the left navigation pane, click `Service accounts`. All service accounts and their corresponding keys are listed.\n3. Click the service account.\n4. Click the `edit` and delete the keys.\n\n**From Command Line**\nRun\n```\ngcloud iam service-accounts keys delete --iam-account=USER_MANAGED_SERVICE_ACCOUNT_EMAIL KEY_ID\n```\n\n**References**\n1. https://cloud.google.com/sdk/gcloud/reference/iam/service-accounts/keys/delete\n2. https://cloud.google.com/iam/docs/understanding-service-accounts#managing_service_accounts\n","complianceTags":"Identity and Access Management","logicHash":"FW9q2DT7EC5veV1iuFY91Q","severity":"High"},"account":{"id":"serious-conduit-389105","name":"GCP Demo Account NU","vendor":"GCP","dome9CloudAccountId":"ca5ef528-d8dd-41d8-a022-1a820a6adb60","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"displayName":"CloudGuard-Connect ","email":"cloudguard-connect@serious-conduit-389105.iam.gserviceaccount.com","oauth2ClientId":"107011996045550659146","projectId":"serious-conduit-389105","uniqueId":"107011996045550659146","keys":[{"keyAlgorithm":"KEY_ALG_RSA_2048","name":"projects/serious-conduit-389105/serviceAccounts/cloudguard-connect@serious-conduit-389105.iam.gserviceaccount.com/keys/73a51b4a085a4fecf512b238220f891ab7af6e33","privateKeyData":null,"privateKeyType":null,"publicKeyData":null,"validAfterTime":1686115964,"validBeforeTime":1750770052,"eTag":null,"managedBy":"System"},{"keyAlgorithm":"KEY_ALG_RSA_2048","name":"projects/serious-conduit-389105/serviceAccounts/cloudguard-connect@serious-conduit-389105.iam.gserviceaccount.com/keys/898ae23e2f6e676386f0dfbedd13b200b148e3db","privateKeyData":null,"privateKeyType":null,"publicKeyData":null,"validAfterTime":1686116146,"validBeforeTime":253402300799,"eTag":null,"managedBy":"User"}],"roles":["roles/cloudasset.viewer","roles/iam.securityReviewer","roles/viewer"],"auditConfigsExemption":null,"selfLink":null,"id":"107011996045550659146","type":"ServiceAccount","name":"projects/serious-conduit-389105/serviceAccounts/cloudguard-connect@serious-conduit-389105.iam.gserviceaccount.com","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|ServiceAccount|projects/serious-conduit-389105/serviceAccounts/cloudguard-connect@serious-conduit-389105.iam.gserviceaccount.com","accountNumber":"serious-conduit-389105","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_37/webhook-1686305238810.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"sC4A0DzUA8w2sOqDuZZd0Q","findingId":"sC4A0DzUA8w2sOqDuZZd0Q","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"GCP CloudGuard Best Practices","description":"CloudGuard Best Practices for securing GCP Account","id":-9},"reportTime":"2023-06-09T09:04:54.86Z","rule":{"name":"Ensure that Service Account has no Admin privileges","ruleId":"D9.GCP.IAM.05","description":"A Service Account is a special Google account that belongs to your application or a VM, instead of to an individual end user. Your application uses the service account to call the Google API of a service, so that the users aren't directly involved It's recommended not to use admin access for Service Account.","remediation":"\n**From Portal**\n1. Go to IAM & admin/IAM using https://console.cloud.google.com/iam-admin/iam\n2. Go to the Principals\n3. Identify the service account with over-permissive roles, click on the edit member icon.\n4. Identify the over-permissive roles and click on the delete bin icon to remove role from the service account.\n\n\n**From Command Line**\n\n1. Get the policy that you want to modify, and write it to a file:\n```\ngcloud projects get-iam-policy PROJECT_ID > PATH_TO_NEWLY_CREATED_FILE\n```\n2. In the created file, detect the overly permissive service account and delete any role containing 'admin', 'roles/owner' or 'roles/editor'\n3. Set the new iam policy of the service account:\n```\ngcloud projects set-iam-policy PROJECT_ID PATH_TO_EDITED_FILE\n```\n\n**References**\n1. https://cloud.google.com/sdk/gcloud/reference/projects/get-iam-policy\n2. https://cloud.google.com/sdk/gcloud/reference/projects/set-iam-policy\n3. https://cloud.google.com/iam/docs/understanding-roles\n4. https://cloud.google.com/iam/docs/understanding-service-accounts\n","complianceTags":"Identity and Access Management","logicHash":"lJY3qAzm2o6SnzsnEOMFJA","severity":"High"},"account":{"id":"serious-conduit-389105","name":"GCP Demo Account NU","vendor":"GCP","dome9CloudAccountId":"ca5ef528-d8dd-41d8-a022-1a820a6adb60","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"displayName":"Compute Engine default service account","email":"554880214893-compute@developer.gserviceaccount.com","oauth2ClientId":"109752848574392986178","projectId":"serious-conduit-389105","uniqueId":"109752848574392986178","keys":[{"keyAlgorithm":"KEY_ALG_RSA_2048","name":"projects/serious-conduit-389105/serviceAccounts/554880214893-compute@developer.gserviceaccount.com/keys/88e7cf6f36b028fbd0057bcce4f7f5f9e905d884","privateKeyData":null,"privateKeyType":null,"publicKeyData":null,"validAfterTime":1686115247,"validBeforeTime":1751169630,"eTag":null,"managedBy":"System"}],"roles":["roles/editor"],"auditConfigsExemption":null,"selfLink":null,"id":"109752848574392986178","type":"ServiceAccount","name":"projects/serious-conduit-389105/serviceAccounts/554880214893-compute@developer.gserviceaccount.com","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|ServiceAccount|projects/serious-conduit-389105/serviceAccounts/554880214893-compute@developer.gserviceaccount.com","accountNumber":"serious-conduit-389105","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}
