=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_36/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "status": {
            "type": "string"
        },
        "policy": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "description",
                "name"
            ]
        },
        "findingKey": {
            "type": "string"
        },
        "findingId": {
            "type": "string"
        },
        "cloudGuardAccountId": {
            "type": "string"
        },
        "origin": {
            "type": "string"
        },
        "bundle": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            },
            "required": [
                "description",
                "id",
                "name"
            ]
        },
        "reportTime": {
            "type": "string"
        },
        "rule": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "ruleId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "remediation": {
                    "type": "string"
                },
                "complianceTags": {
                    "type": "string"
                },
                "logicHash": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                }
            },
            "required": [
                "complianceTags",
                "description",
                "logicHash",
                "name",
                "remediation",
                "ruleId",
                "severity"
            ]
        },
        "account": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                },
                "dome9CloudAccountId": {
                    "type": "string"
                },
                "organizationalUnitId": {
                    "type": "string"
                },
                "organizationalUnitPath": {
                    "type": "string"
                }
            },
            "required": [
                "dome9CloudAccountId",
                "id",
                "name",
                "organizationalUnitId",
                "organizationalUnitPath",
                "vendor"
            ]
        },
        "region": {
            "type": "string"
        },
        "entity": {
            "type": "object",
            "properties": {
                "network": {
                    "type": "string"
                },
                "inboundRules": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "description": {
                                "type": "string"
                            },
                            "enabled": {
                                "type": "boolean"
                            },
                            "name": {
                                "type": "string"
                            },
                            "number": {
                                "type": "integer"
                            },
                            "protocol": {
                                "type": "string"
                            },
                            "source": {
                                "type": "string"
                            },
                            "destination": {
                                "type": "string"
                            },
                            "destinationPort": {
                                "type": "integer"
                            },
                            "destinationPortTo": {
                                "type": "integer"
                            },
                            "direction": {
                                "type": "string"
                            },
                            "action": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "action",
                            "description",
                            "destination",
                            "destinationPort",
                            "destinationPortTo",
                            "direction",
                            "enabled",
                            "name",
                            "number",
                            "protocol",
                            "source"
                        ]
                    }
                },
                "outboundRules": {
                    "type": "array"
                },
                "vmInstances": {
                    "type": "array"
                },
                "resourceType": {
                    "type": "string"
                },
                "selfLink": {
                    "type": "null"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "dome9Id": {
                    "type": "string"
                },
                "accountNumber": {
                    "type": "string"
                },
                "assetLabels": {
                    "type": "null"
                },
                "region": {
                    "type": "string"
                },
                "externalFindings": {
                    "type": "null"
                }
            },
            "required": [
                "accountNumber",
                "assetLabels",
                "dome9Id",
                "externalFindings",
                "id",
                "inboundRules",
                "name",
                "network",
                "outboundRules",
                "region",
                "resourceType",
                "selfLink",
                "type",
                "vmInstances"
            ]
        },
        "remediationActions": {
            "type": "array"
        },
        "action": {
            "type": "string"
        },
        "additionalFields": {
            "type": "array"
        }
    },
    "required": [
        "account",
        "action",
        "additionalFields",
        "bundle",
        "cloudGuardAccountId",
        "entity",
        "findingId",
        "findingKey",
        "origin",
        "policy",
        "region",
        "remediationActions",
        "reportTime",
        "rule",
        "status"
    ]
}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_36/webhook-1686305234685.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"Q32a2KsU12FmR9WBLxc8eA","findingId":"Q32a2KsU12FmR9WBLxc8eA","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"GCP CloudGuard Best Practices","description":"CloudGuard Best Practices for securing GCP Account","id":-9},"reportTime":"2023-06-09T09:04:54.86Z","rule":{"name":"Ensure Global Firewall rule should not allows all traffic","ruleId":"D9.GCP.NET.07","description":"Firewall Rules that are applied to all the VM instances - 'Global' should not allow protocol='TCP' and source = '0.0.0.0/0' ","remediation":"\n**From Portal**\n1. Go to VPC network.\n2. Go to the Firewall Rules.\n3. Select the relevant Firewall Rule and click on Edit.\n3. Ensure Port is not equal to 22 and Action is not Allow.\n4. Under Source ranges ensure IP Ranges is not equal to 0.0.0.0 .\n\n\n**From Command Line**\nNote : If you need to change the name, network, or the action or direction component, you must delete the rule and create a new one instead.\n\n1. To update exist firewall rules, run:\n```\ngcloud compute firewall-rules update FIREWALL_NAME --source-ranges=CIDR_RANGE --rules=[PROTOCOL[:PORT]\n```\n2. To delete firewall rules, run:\n```\ngcloud compute firewall-rules delete [FIREWALL_NAME]\n```\n3. To create new firewall rules, run:\n```\ngcloud compute firewall-rules create FIREWALL_NAME\n[--priority=PRIORITY] \n[--description=DESCRIPTION] \n[--target-tags=TAG,...] \n[--target-service-accounts=IAM_SERVICE_ACCOUNT,_] \n[--source-ranges=CIDR_RANGE,...] \n[--source-tags=TAG,...] \n[--source-service-accounts=IAM_SERVICE_ACCOUNT,_] \n[--destination-ranges=CIDR_RANGE,...] \n[--rules=[JHY[:88[-88]],...]] \n[--disabled | --no-disabled] \n[--enable-logging | --no-enable-logging]\n```\n\n**From TF**\n```\nresource \"google_compute_firewall\" \"allow-ssh\" {\nname = \"global\"\nallow {\n-   protocol = \"tcp\"\n}\n- source_ranges = [\"0.0.0.0/0\"]\n}\n```\n\n**References**\n1. https://cloud.google.com/vpc/docs/firewalls#blockedtraffic\n2. https://cloud.google.com/vpc/docs/using-firewalls\n","complianceTags":"Network Security","logicHash":"pPkl2a1+LTaeRiQY8jK+iA","severity":"High"},"account":{"id":"serious-conduit-389105","name":"GCP Demo Account NU","vendor":"GCP","dome9CloudAccountId":"ca5ef528-d8dd-41d8-a022-1a820a6adb60","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"network":"default","inboundRules":[{"description":"Allow ICMP from anywhere","enabled":true,"name":"default-allow-icmp","number":65534,"protocol":"ICMP","source":"0.0.0.0/0","destination":"0.0.0.0/0","destinationPort":0,"destinationPortTo":0,"direction":"INBOUND","action":"ALLOW"},{"description":"Allow SSH from anywhere","enabled":true,"name":"default-allow-ssh","number":65534,"protocol":"TCP","source":"0.0.0.0/0","destination":"0.0.0.0/0","destinationPort":22,"destinationPortTo":22,"direction":"INBOUND","action":"ALLOW"},{"description":"Allow internal traffic on the default network","enabled":true,"name":"default-allow-internal","number":65534,"protocol":"TCP","source":"10.128.0.0/9","destination":"0.0.0.0/0","destinationPort":0,"destinationPortTo":65535,"direction":"INBOUND","action":"ALLOW"},{"description":"Allow internal traffic on the default network","enabled":true,"name":"default-allow-internal","number":65534,"protocol":"UDP","source":"10.128.0.0/9","destination":"0.0.0.0/0","destinationPort":0,"destinationPortTo":65535,"direction":"INBOUND","action":"ALLOW"},{"description":"Allow internal traffic on the default network","enabled":true,"name":"default-allow-internal","number":65534,"protocol":"ICMP","source":"10.128.0.0/9","destination":"0.0.0.0/0","destinationPort":0,"destinationPortTo":0,"direction":"INBOUND","action":"ALLOW"},{"description":"Allow RDP from anywhere","enabled":true,"name":"default-allow-rdp","number":65534,"protocol":"TCP","source":"0.0.0.0/0","destination":"0.0.0.0/0","destinationPort":3389,"destinationPortTo":3389,"direction":"INBOUND","action":"ALLOW"}],"outboundRules":[],"vmInstances":[],"resourceType":"Local","selfLink":null,"id":"serious-conduit-389105|default|global","type":"GcpSecurityGroup","name":"Global","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|SecurityGroup|serious-conduit-389105|default|global","accountNumber":"serious-conduit-389105","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_36/webhook-1686305214011.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"6yQoRQztEmHH6ePiI2JkLQ","findingId":"6yQoRQztEmHH6ePiI2JkLQ","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"GCP CloudGuard Best Practices","description":"CloudGuard Best Practices for securing GCP Account","id":-9},"reportTime":"2023-06-09T09:04:54.86Z","rule":{"name":"Ensure that RDP access is restricted from the internet","ruleId":"D9.GCP.NET.13","description":"GCP Firewall Rules are specific to a VPC Network. Each rule either allows or denies traffic when its conditions are met. Its conditions allow you to specify the type of traffic, such as ports and protocols, and the source or destination of the traffic, including IP addresses, subnets, and instances. Firewall rules are defined at the VPC network level, and are specific to the network in which they are defined. The rules themselves cannot be shared among networks. Firewall rules only support IPv4 traffic. When specifying a source for an ingress rule or a destination for an egress rule by address, you can only use an IPv4 address or IPv4 block in CIDR notation. Generic (0.0.0.0/0) incoming traffic from internet to VPC or VM instance using RDP on Port 3389 can be avoided.","remediation":"\n**From Portal**\n1. Go to VPC Network.\n2. Go to the Firewall Rules.\n3. Click the Firewall Rule you want to modify.\n4. Click Edit.\n5. Modify Source IP ranges to specific IP.\n6. Click Save.\n\n**From TF**\nSet deny bucket to be equal to protocol:tcp, port:3389:\n```\nresource 'google_compute_firewall' 'default' {\n...\ndeny {\nprotocol = 'tcp'\nports    = ['3389']\n}\n...\n}\n```\n\n**From Command Line**\nRun\n```\ngcloud compute firewall-rules update FIREWALL_NAME --rules=PROTOCOL:PORT-PORT\n```\n\n**References**\n1. https://cloud.google.com/vpc/docs/firewalls#default_firewall_rules\n2. https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_firewall\n","complianceTags":"Network Security","logicHash":"1hkXWeXTcN2vGUEKlR17jg","severity":"High"},"account":{"id":"serious-conduit-389105","name":"GCP Demo Account NU","vendor":"GCP","dome9CloudAccountId":"ca5ef528-d8dd-41d8-a022-1a820a6adb60","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"network":"default","inboundRules":[{"description":"Allow ICMP from anywhere","enabled":true,"name":"default-allow-icmp","number":65534,"protocol":"ICMP","source":"0.0.0.0/0","destination":"0.0.0.0/0","destinationPort":0,"destinationPortTo":0,"direction":"INBOUND","action":"ALLOW"},{"description":"Allow SSH from anywhere","enabled":true,"name":"default-allow-ssh","number":65534,"protocol":"TCP","source":"0.0.0.0/0","destination":"0.0.0.0/0","destinationPort":22,"destinationPortTo":22,"direction":"INBOUND","action":"ALLOW"},{"description":"Allow internal traffic on the default network","enabled":true,"name":"default-allow-internal","number":65534,"protocol":"TCP","source":"10.128.0.0/9","destination":"0.0.0.0/0","destinationPort":0,"destinationPortTo":65535,"direction":"INBOUND","action":"ALLOW"},{"description":"Allow internal traffic on the default network","enabled":true,"name":"default-allow-internal","number":65534,"protocol":"UDP","source":"10.128.0.0/9","destination":"0.0.0.0/0","destinationPort":0,"destinationPortTo":65535,"direction":"INBOUND","action":"ALLOW"},{"description":"Allow internal traffic on the default network","enabled":true,"name":"default-allow-internal","number":65534,"protocol":"ICMP","source":"10.128.0.0/9","destination":"0.0.0.0/0","destinationPort":0,"destinationPortTo":0,"direction":"INBOUND","action":"ALLOW"},{"description":"Allow RDP from anywhere","enabled":true,"name":"default-allow-rdp","number":65534,"protocol":"TCP","source":"0.0.0.0/0","destination":"0.0.0.0/0","destinationPort":3389,"destinationPortTo":3389,"direction":"INBOUND","action":"ALLOW"}],"outboundRules":[],"vmInstances":[],"resourceType":"Local","selfLink":null,"id":"serious-conduit-389105|default|global","type":"GcpSecurityGroup","name":"Global","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|SecurityGroup|serious-conduit-389105|default|global","accountNumber":"serious-conduit-389105","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}
