=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_15/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "status": {
            "type": "string"
        },
        "policy": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "description",
                "name"
            ]
        },
        "findingKey": {
            "type": "string"
        },
        "findingId": {
            "type": "string"
        },
        "cloudGuardAccountId": {
            "type": "string"
        },
        "origin": {
            "type": "string"
        },
        "bundle": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            },
            "required": [
                "description",
                "id",
                "name"
            ]
        },
        "reportTime": {
            "type": "string"
        },
        "rule": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "ruleId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "remediation": {
                    "type": "string"
                },
                "complianceTags": {
                    "type": "string"
                },
                "logicHash": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                }
            },
            "required": [
                "complianceTags",
                "description",
                "logicHash",
                "name",
                "remediation",
                "ruleId",
                "severity"
            ]
        },
        "account": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                },
                "dome9CloudAccountId": {
                    "type": "string"
                },
                "organizationalUnitId": {
                    "type": "string"
                },
                "organizationalUnitPath": {
                    "type": "string"
                }
            },
            "required": [
                "dome9CloudAccountId",
                "id",
                "name",
                "organizationalUnitId",
                "organizationalUnitPath",
                "vendor"
            ]
        },
        "region": {
            "type": "string"
        },
        "entity": {
            "type": "object",
            "properties": {
                "rules": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "apiGroups": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "nonResourceURLs": {
                                "type": "null"
                            },
                            "resourceNames": {
                                "type": "null"
                            },
                            "resources": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "verbs": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        },
                        "required": [
                            "apiGroups",
                            "nonResourceURLs",
                            "resourceNames",
                            "resources",
                            "verbs"
                        ]
                    }
                },
                "aggregationRule": {
                    "type": "null"
                },
                "roleBindings": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "namespace": {
                                "type": "string"
                            },
                            "kind": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "kind",
                            "name",
                            "namespace"
                        ]
                    }
                },
                "kind": {
                    "type": "string"
                },
                "tags": {
                    "type": "array"
                },
                "namespace": {
                    "type": "string"
                },
                "annotations": {
                    "type": "array"
                },
                "labels": {
                    "type": "array"
                },
                "creationTime": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "dome9Id": {
                    "type": "string"
                },
                "accountNumber": {
                    "type": "string"
                },
                "assetLabels": {
                    "type": "null"
                },
                "region": {
                    "type": "string"
                },
                "externalFindings": {
                    "type": "null"
                }
            },
            "required": [
                "accountNumber",
                "aggregationRule",
                "annotations",
                "assetLabels",
                "creationTime",
                "dome9Id",
                "externalFindings",
                "id",
                "kind",
                "labels",
                "name",
                "namespace",
                "region",
                "roleBindings",
                "rules",
                "tags",
                "type"
            ]
        },
        "remediationActions": {
            "type": "array"
        },
        "action": {
            "type": "string"
        },
        "additionalFields": {
            "type": "array"
        }
    },
    "required": [
        "account",
        "action",
        "additionalFields",
        "bundle",
        "cloudGuardAccountId",
        "entity",
        "findingId",
        "findingKey",
        "origin",
        "policy",
        "region",
        "remediationActions",
        "reportTime",
        "rule",
        "status"
    ]
}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/webhook-1686308456038.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"4yfHzuzVr34o4t2m1Reskg","findingId":"4yfHzuzVr34o4t2m1Reskg","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"CIS Kubernetes Benchmark v1.6.1","description":"Automated Validation of Kubernetes CIS Benchmark v1.6.1 Prescriptive guidance for establishing a secure configuration posture for Kubernetes 1.6.1\nFor additional reference: https://www.cisecurity.org/benchmark/kubernetes/","id":-70},"reportTime":"2023-06-09T11:00:31.243Z","rule":{"name":"Minimize wildcard use in Roles and ClusterRoles (RBAC)","ruleId":"D9.K8S.IAM.34","description":"Kubernetes Roles and ClusterRoles provide access to resources based on sets of objects and actions that can be taken on those objects. It is possible to set either of these to be the wildcard ' * ' which matches all items. Use of wildcards is not optimal from a security perspective as it may allow for inadvertent access to be granted when new resources are added to the Kubernetes API either as CRDs or in later versions of the product. The principle of least privilege recommends that users are provided only the access required for their role and nothing more. The use of wildcard rights grants is likely to provide excessive rights to the Kubernetes API.","remediation":"Where possible replace any use of wildcards in clusterroles and roles with specific objects or actions.","complianceTags":"5.1.3","logicHash":"DwVAEgpl3v1hkhfDMwMnvA","severity":"Low"},"account":{"id":"5af13ab5-72ed-43b6-9544-33c9236d62f0","name":"nu-openshift-cluster","vendor":"Kubernetes","dome9CloudAccountId":"5af13ab5-72ed-43b6-9544-33c9236d62f0","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"rules":[{"apiGroups":["","rbac.authorization.k8s.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["secrets","pods","serviceaccounts","roles","rolebindings","services","services/finalizers","endpoints","persistentvolumeclaims","events","configmaps","jobs","pods/exec","pods/log"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["apps"],"nonResourceURLs":null,"resourceNames":null,"resources":["deployments","daemonsets","replicasets","statefulsets","jobs"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["monitoring.coreos.com"],"nonResourceURLs":null,"resourceNames":null,"resources":["servicemonitors"],"verbs":["get","create"]},{"apiGroups":["tower.ansible.com"],"nonResourceURLs":null,"resourceNames":null,"resources":["ansiblejobs","ansiblejobs/status","ansiblejobs/finalizers"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["tower.ansible.com"],"nonResourceURLs":null,"resourceNames":null,"resources":["jobtemplates","jobtemplates/status","jobtemplates/finalizers"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["apps"],"nonResourceURLs":null,"resourceNames":["resource-operator-controller-manager"],"resources":["deployments/finalizers"],"verbs":["update"]},{"apiGroups":[""],"nonResourceURLs":null,"resourceNames":null,"resources":["pods","jobs"],"verbs":["get"]},{"apiGroups":["apps"],"nonResourceURLs":null,"resourceNames":null,"resources":["replicasets","deployments","jobs"],"verbs":["get"]},{"apiGroups":["tower.ansible.com"],"nonResourceURLs":null,"resourceNames":null,"resources":["*"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["batch"],"nonResourceURLs":null,"resourceNames":null,"resources":["*"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":[""],"nonResourceURLs":null,"resourceNames":null,"resources":["configmaps"],"verbs":["get","list","watch","create","update","patch","delete"]},{"apiGroups":["coordination.k8s.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["leases"],"verbs":["get","list","watch","create","update","patch","delete"]},{"apiGroups":[""],"nonResourceURLs":null,"resourceNames":null,"resources":["events"],"verbs":["create","patch"]}],"aggregationRule":null,"roleBindings":[{"name":"aap-operator.v2.2.1-0.1674769232-d654d6fdc","namespace":"*","kind":"ClusterRoleBinding"}],"kind":"ClusterRole","tags":[{"key":"olm.owner","value":"aap-operator.v2.2.1-0.1674769232"},{"key":"olm.owner.kind","value":"ClusterServiceVersion"},{"key":"olm.owner.namespace","value":"ansible-automation-platform"},{"key":"operators.coreos.com/ansible-automation-platform-operator.ansible-automation-platfor","value":""}],"namespace":"*","annotations":[],"labels":[{"key":"olm.owner","value":"aap-operator.v2.2.1-0.1674769232"},{"key":"olm.owner.kind","value":"ClusterServiceVersion"},{"key":"olm.owner.namespace","value":"ansible-automation-platform"},{"key":"operators.coreos.com/ansible-automation-platform-operator.ansible-automation-platfor","value":""}],"creationTime":1675115470,"id":"fe20a9e6-a97f-4e50-9cb7-95f225e13668","type":"KubernetesRole","name":"aap-operator.v2.2.1-0.1674769232-d654d6fdc","dome9Id":"11|5af13ab5-72ed-43b6-9544-33c9236d62f0|ClusterRole|fe20a9e6-a97f-4e50-9cb7-95f225e13668","accountNumber":"5af13ab5-72ed-43b6-9544-33c9236d62f0","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_26/webhook-1686308538848.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"me3fcHwqemG2yna4RCCBKA","findingId":"me3fcHwqemG2yna4RCCBKA","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"CIS Kubernetes Benchmark v1.6.1","description":"Automated Validation of Kubernetes CIS Benchmark v1.6.1 Prescriptive guidance for establishing a secure configuration posture for Kubernetes 1.6.1\nFor additional reference: https://www.cisecurity.org/benchmark/kubernetes/","id":-70},"reportTime":"2023-06-09T11:00:31.243Z","rule":{"name":"Minimize wildcard use in Roles and ClusterRoles (RBAC)","ruleId":"D9.K8S.IAM.34","description":"Kubernetes Roles and ClusterRoles provide access to resources based on sets of objects and actions that can be taken on those objects. It is possible to set either of these to be the wildcard ' * ' which matches all items. Use of wildcards is not optimal from a security perspective as it may allow for inadvertent access to be granted when new resources are added to the Kubernetes API either as CRDs or in later versions of the product. The principle of least privilege recommends that users are provided only the access required for their role and nothing more. The use of wildcard rights grants is likely to provide excessive rights to the Kubernetes API.","remediation":"Where possible replace any use of wildcards in clusterroles and roles with specific objects or actions.","complianceTags":"5.1.3","logicHash":"DwVAEgpl3v1hkhfDMwMnvA","severity":"Low"},"account":{"id":"5af13ab5-72ed-43b6-9544-33c9236d62f0","name":"nu-openshift-cluster","vendor":"Kubernetes","dome9CloudAccountId":"5af13ab5-72ed-43b6-9544-33c9236d62f0","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"rules":[{"apiGroups":[""],"nonResourceURLs":null,"resourceNames":null,"resources":["nodes"],"verbs":["get","list","watch"]},{"apiGroups":[""],"nonResourceURLs":null,"resourceNames":null,"resources":["events"],"verbs":["list"]},{"apiGroups":["imageregistry.operator.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["configs","imagepruners"],"verbs":["get","list","watch"]},{"apiGroups":[""],"nonResourceURLs":null,"resourceNames":null,"resources":["nodes"],"verbs":["proxy"]},{"apiGroups":[""],"nonResourceURLs":null,"resourceNames":null,"resources":["nodes/log","nodes/metrics","nodes/proxy","nodes/stats"],"verbs":["get"]},{"apiGroups":["config.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["policy"],"nonResourceURLs":null,"resourceNames":null,"resources":["poddisruptionbudgets"],"verbs":["list","get","watch"]},{"apiGroups":["machine.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["machinesets"],"verbs":["get","list","watch"]},{"apiGroups":["operator.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["installers.datahub.sap.com"],"nonResourceURLs":null,"resourceNames":null,"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["operators.coreos.com"],"nonResourceURLs":null,"resourceNames":null,"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["controlplane.operator.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["podnetworkconnectivitychecks"],"verbs":["get","list","watch"]},{"apiGroups":["machineconfiguration.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["machineconfigs"],"verbs":["get","list","watch"]},{"apiGroups":["logging.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["apiserver.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["apirequestcounts"],"verbs":["get","list","watch"]},{"apiGroups":["jaegertracing.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["jaegers"],"verbs":["get","list","watch"]},{"apiGroups":["costmanagement-metrics-cfg.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["costmanagementmetricsconfigs"],"verbs":["get","list","watch"]},{"apiGroups":["ocs.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["storageclusters"],"verbs":["get","list"]},{"apiGroups":["ceph.rook.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["cephclusters"],"verbs":["get","list"]}],"aggregationRule":null,"roleBindings":[{"name":"insights-operator-gather","namespace":"*","kind":"ClusterRoleBinding"}],"kind":"ClusterRole","tags":[],"namespace":"*","annotations":[{"key":"include.release.openshift.io/ibm-cloud-managed","value":"true"},{"key":"include.release.openshift.io/self-managed-high-availability","value":"true"},{"key":"include.release.openshift.io/single-node-developer","value":"true"}],"labels":[],"creationTime":1667113732,"id":"9df000e2-76ed-4184-8ae4-3ea36469118a","type":"KubernetesRole","name":"insights-operator-gather","dome9Id":"11|5af13ab5-72ed-43b6-9544-33c9236d62f0|ClusterRole|9df000e2-76ed-4184-8ae4-3ea36469118a","accountNumber":"5af13ab5-72ed-43b6-9544-33c9236d62f0","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/webhook-1686308535732.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"m5rIXmkV6HE94cmY9MMq1A","findingId":"m5rIXmkV6HE94cmY9MMq1A","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"CIS Kubernetes Benchmark v1.6.1","description":"Automated Validation of Kubernetes CIS Benchmark v1.6.1 Prescriptive guidance for establishing a secure configuration posture for Kubernetes 1.6.1\nFor additional reference: https://www.cisecurity.org/benchmark/kubernetes/","id":-70},"reportTime":"2023-06-09T11:00:31.243Z","rule":{"name":"Minimize access to secrets (RBAC)","ruleId":"D9.K8S.IAM.33","description":"The Kubernetes API stores secrets, which may be service account tokens for the Kubernetes API or credentials used by workloads in the cluster. Access to these secrets should be restricted to the smallest possible group of users to reduce the risk of privilege escalation. Inappropriate access to secrets stored within the Kubernetes cluster can allow for an attacker to gain additional access to the Kubernetes cluster or external resources whose credentials are stored as secrets.","remediation":"Where possible, remove get, list and watch access to secret objects in the cluster.","complianceTags":"5.1.2","logicHash":"w/IX39GnXfBqt1rAGIV/eA","severity":"Low"},"account":{"id":"5af13ab5-72ed-43b6-9544-33c9236d62f0","name":"nu-openshift-cluster","vendor":"Kubernetes","dome9CloudAccountId":"5af13ab5-72ed-43b6-9544-33c9236d62f0","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"rules":[{"apiGroups":["metrics.k8s.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["*"],"verbs":["*"]}],"aggregationRule":null,"roleBindings":[],"kind":"ClusterRole","tags":[{"key":"app.kubernetes.io/component","value":"metrics-adapter"},{"key":"app.kubernetes.io/name","value":"prometheus-adapter"},{"key":"app.kubernetes.io/part-of","value":"openshift-monitoring"},{"key":"app.kubernetes.io/version","value":"0.9.1"}],"namespace":"*","annotations":[],"labels":[{"key":"app.kubernetes.io/component","value":"metrics-adapter"},{"key":"app.kubernetes.io/name","value":"prometheus-adapter"},{"key":"app.kubernetes.io/part-of","value":"openshift-monitoring"},{"key":"app.kubernetes.io/version","value":"0.9.1"}],"creationTime":1667114327,"id":"545b9012-be7f-4b25-9625-0aaf0d218e98","type":"KubernetesRole","name":"resource-metrics-server-resources","dome9Id":"11|5af13ab5-72ed-43b6-9544-33c9236d62f0|ClusterRole|545b9012-be7f-4b25-9625-0aaf0d218e98","accountNumber":"5af13ab5-72ed-43b6-9544-33c9236d62f0","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/webhook-1686308483805.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"bPIjTkI6kNsklJbjjle0rw","findingId":"bPIjTkI6kNsklJbjjle0rw","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"CIS Kubernetes Benchmark v1.6.1","description":"Automated Validation of Kubernetes CIS Benchmark v1.6.1 Prescriptive guidance for establishing a secure configuration posture for Kubernetes 1.6.1\nFor additional reference: https://www.cisecurity.org/benchmark/kubernetes/","id":-70},"reportTime":"2023-06-09T11:00:31.243Z","rule":{"name":"Minimize wildcard use in Roles and ClusterRoles (RBAC)","ruleId":"D9.K8S.IAM.34","description":"Kubernetes Roles and ClusterRoles provide access to resources based on sets of objects and actions that can be taken on those objects. It is possible to set either of these to be the wildcard ' * ' which matches all items. Use of wildcards is not optimal from a security perspective as it may allow for inadvertent access to be granted when new resources are added to the Kubernetes API either as CRDs or in later versions of the product. The principle of least privilege recommends that users are provided only the access required for their role and nothing more. The use of wildcard rights grants is likely to provide excessive rights to the Kubernetes API.","remediation":"Where possible replace any use of wildcards in clusterroles and roles with specific objects or actions.","complianceTags":"5.1.3","logicHash":"DwVAEgpl3v1hkhfDMwMnvA","severity":"Low"},"account":{"id":"5af13ab5-72ed-43b6-9544-33c9236d62f0","name":"nu-openshift-cluster","vendor":"Kubernetes","dome9CloudAccountId":"5af13ab5-72ed-43b6-9544-33c9236d62f0","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"rules":[{"apiGroups":["apiextensions.k8s.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["customresourcedefinitions","customresourcedefinitions/status"],"verbs":["get","list","watch"]},{"apiGroups":["k8s.cni.cncf.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":[""],"nonResourceURLs":null,"resourceNames":null,"resources":["namespaces"],"verbs":["get","list","watch"]},{"apiGroups":[""],"nonResourceURLs":null,"resourceNames":null,"resources":["pods/status"],"verbs":["get","list","watch","patch","update"]},{"apiGroups":[""],"nonResourceURLs":null,"resourceNames":null,"resources":["pods"],"verbs":["get","list","watch"]},{"apiGroups":["","events.k8s.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["events"],"verbs":["create","patch","update"]}],"aggregationRule":null,"roleBindings":[{"name":"multus","namespace":"*","kind":"ClusterRoleBinding"}],"kind":"ClusterRole","tags":[],"namespace":"*","annotations":[],"labels":[],"creationTime":1667113811,"id":"678ffb6f-946b-46a8-97ea-19dece04bc10","type":"KubernetesRole","name":"multus","dome9Id":"11|5af13ab5-72ed-43b6-9544-33c9236d62f0|ClusterRole|678ffb6f-946b-46a8-97ea-19dece04bc10","accountNumber":"5af13ab5-72ed-43b6-9544-33c9236d62f0","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/webhook-1686308551697.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"OTEMh3lBsqK5b0+Ou0nZOg","findingId":"OTEMh3lBsqK5b0+Ou0nZOg","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"CIS Kubernetes Benchmark v1.6.1","description":"Automated Validation of Kubernetes CIS Benchmark v1.6.1 Prescriptive guidance for establishing a secure configuration posture for Kubernetes 1.6.1\nFor additional reference: https://www.cisecurity.org/benchmark/kubernetes/","id":-70},"reportTime":"2023-06-09T11:00:31.243Z","rule":{"name":"Minimize wildcard use in Roles and ClusterRoles (RBAC)","ruleId":"D9.K8S.IAM.34","description":"Kubernetes Roles and ClusterRoles provide access to resources based on sets of objects and actions that can be taken on those objects. It is possible to set either of these to be the wildcard ' * ' which matches all items. Use of wildcards is not optimal from a security perspective as it may allow for inadvertent access to be granted when new resources are added to the Kubernetes API either as CRDs or in later versions of the product. The principle of least privilege recommends that users are provided only the access required for their role and nothing more. The use of wildcard rights grants is likely to provide excessive rights to the Kubernetes API.","remediation":"Where possible replace any use of wildcards in clusterroles and roles with specific objects or actions.","complianceTags":"5.1.3","logicHash":"DwVAEgpl3v1hkhfDMwMnvA","severity":"Low"},"account":{"id":"5af13ab5-72ed-43b6-9544-33c9236d62f0","name":"nu-openshift-cluster","vendor":"Kubernetes","dome9CloudAccountId":"5af13ab5-72ed-43b6-9544-33c9236d62f0","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"rules":[{"apiGroups":["imageregistry.operator.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["configs","configs/status","imagepruners","imagepruners/status"],"verbs":["*"]},{"apiGroups":["config.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["clusteroperators","images","images/status"],"verbs":["*"]},{"apiGroups":["config.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["infrastructures"],"verbs":["get","list","watch"]},{"apiGroups":[""],"nonResourceURLs":null,"resourceNames":null,"resources":["configmaps","endpoints","events","namespaces","persistentvolumeclaims","pods","secrets","services"],"verbs":["*"]},{"apiGroups":[""],"nonResourceURLs":null,"resourceNames":null,"resources":["serviceaccounts"],"verbs":["*"]},{"apiGroups":["rbac.authorization.k8s.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["clusterroles","clusterrolebindings"],"verbs":["*"]},{"apiGroups":[""],"nonResourceURLs":null,"resourceNames":null,"resources":["limitranges","resourcequotas","nodes"],"verbs":["list"]},{"apiGroups":["image.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["*"],"verbs":["*"]},{"apiGroups":["route.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["routes","routes/custom-host"],"verbs":["*"]},{"apiGroups":["config.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["clusteroperators","clusteroperators/status"],"verbs":["create","get","update"]},{"apiGroups":["config.openshift.io"],"nonResourceURLs":null,"resourceNames":null,"resources":["proxies"],"verbs":["list","get","watch"]}],"aggregationRule":null,"roleBindings":[{"name":"default-account-cluster-image-registry-operator","namespace":"*","kind":"ClusterRoleBinding"}],"kind":"ClusterRole","tags":[],"namespace":"*","annotations":[{"key":"include.release.openshift.io/ibm-cloud-managed","value":"true"},{"key":"include.release.openshift.io/self-managed-high-availability","value":"true"},{"key":"include.release.openshift.io/single-node-developer","value":"true"}],"labels":[],"creationTime":1667113738,"id":"6084925b-f4b1-485a-8b5a-f1c1687b4ce4","type":"KubernetesRole","name":"cluster-image-registry-operator","dome9Id":"11|5af13ab5-72ed-43b6-9544-33c9236d62f0|ClusterRole|6084925b-f4b1-485a-8b5a-f1c1687b4ce4","accountNumber":"5af13ab5-72ed-43b6-9544-33c9236d62f0","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}
