=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_20/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "status": {
            "type": "string"
        },
        "policy": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "description",
                "name"
            ]
        },
        "findingKey": {
            "type": "string"
        },
        "findingId": {
            "type": "string"
        },
        "cloudGuardAccountId": {
            "type": "string"
        },
        "origin": {
            "type": "string"
        },
        "bundle": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            },
            "required": [
                "description",
                "id",
                "name"
            ]
        },
        "reportTime": {
            "type": "string"
        },
        "rule": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "ruleId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "remediation": {
                    "type": "string"
                },
                "complianceTags": {
                    "type": "string"
                },
                "logicHash": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                }
            },
            "required": [
                "complianceTags",
                "description",
                "logicHash",
                "name",
                "remediation",
                "ruleId",
                "severity"
            ]
        },
        "account": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                },
                "dome9CloudAccountId": {
                    "type": "string"
                },
                "organizationalUnitId": {
                    "type": "string"
                },
                "organizationalUnitPath": {
                    "type": "string"
                }
            },
            "required": [
                "dome9CloudAccountId",
                "id",
                "name",
                "organizationalUnitId",
                "organizationalUnitPath",
                "vendor"
            ]
        },
        "region": {
            "type": "string"
        },
        "entity": {
            "type": "object",
            "properties": {
                "defaultServiceAccount": {
                    "type": "string"
                },
                "description": {
                    "type": "null"
                },
                "enabledFeatures": {
                    "type": "null"
                },
                "metadata": {
                    "type": "object",
                    "properties": {
                        "items": {
                            "type": "null"
                        },
                        "eTag": {
                            "type": "null"
                        },
                        "kind": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "eTag",
                        "items",
                        "kind"
                    ]
                },
                "sharedVpcHostProjectId": {
                    "type": "null"
                },
                "enabledServices": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "title": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "title"
                        ]
                    }
                },
                "projectNumber": {
                    "type": "string"
                },
                "lifecycleState": {
                    "type": "string"
                },
                "createTime": {
                    "type": "integer"
                },
                "labels": {
                    "type": "null"
                },
                "accessApprovalSettings": {
                    "type": "null"
                },
                "selfLink": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "dome9Id": {
                    "type": "string"
                },
                "accountNumber": {
                    "type": "string"
                },
                "assetLabels": {
                    "type": "null"
                },
                "region": {
                    "type": "string"
                },
                "externalFindings": {
                    "type": "null"
                }
            },
            "required": [
                "accessApprovalSettings",
                "accountNumber",
                "assetLabels",
                "createTime",
                "defaultServiceAccount",
                "description",
                "dome9Id",
                "enabledFeatures",
                "enabledServices",
                "externalFindings",
                "id",
                "labels",
                "lifecycleState",
                "metadata",
                "name",
                "projectNumber",
                "region",
                "selfLink",
                "sharedVpcHostProjectId",
                "type"
            ]
        },
        "remediationActions": {
            "type": "array"
        },
        "action": {
            "type": "string"
        },
        "additionalFields": {
            "type": "array"
        }
    },
    "required": [
        "account",
        "action",
        "additionalFields",
        "bundle",
        "cloudGuardAccountId",
        "entity",
        "findingId",
        "findingKey",
        "origin",
        "policy",
        "region",
        "remediationActions",
        "reportTime",
        "rule",
        "status"
    ]
}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/webhook-1686305223907.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"feNvlodmvO8kA/mbXLRb2Q","findingId":"feNvlodmvO8kA/mbXLRb2Q","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"GCP CloudGuard Best Practices","description":"CloudGuard Best Practices for securing GCP Account","id":-9},"reportTime":"2023-06-09T09:04:54.86Z","rule":{"name":"Ensure oslogin is enabled for a Project","ruleId":"D9.GCP.CRY.03","description":"Enabling osLogin ensures that SSH keys used to connect to instances are mapped with IAM users. Revoking access to IAM user will revoke all the SSH keys associated with that particular user. It facilitates centralized and automated ssh key pair management which is useful in handling cases like response to compromised ssh key pairs and/or revocation of external/third-party/Vendor users.","remediation":"\n**From Portal**\n1. Go to the VM compute metadata page using https://console.cloud.google.com/compute/metadata?\n2. Click Edit.\n3. Add a metadata entry where the key is enable-oslogin and the value is TRUE.\n4. Click Save to apply the changes.\n\n**From TF**\nSet the enable-oslogin to true in metadata node:\n```\nresource 'google_compute_project_metadata' 'default' {\n..\nmetadata = {\nenable-oslogin = true\n}\n..\n}\n```\n\n**From Command Line**\nRun\n```\ngcloud compute project-info add-metadata --metadata enable-oslogin=TRUE\n```\n\n**References**\n1. https://cloud.google.com/compute/docs/storing-retrieving-metadata\n2. https://cloud.google.com/sdk/gcloud/reference/compute/project-info/add-metadata\n","complianceTags":"Encryption and Key Management","logicHash":"Xc6RopEaYTz9xyAlWKAuMQ","severity":"Medium"},"account":{"id":"serious-conduit-389105","name":"GCP Demo Account NU","vendor":"GCP","dome9CloudAccountId":"ca5ef528-d8dd-41d8-a022-1a820a6adb60","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"defaultServiceAccount":"554880214893-compute@developer.gserviceaccount.com","description":null,"enabledFeatures":null,"metadata":{"items":null,"eTag":null,"kind":"compute#metadata"},"sharedVpcHostProjectId":null,"enabledServices":[{"name":"logging.googleapis.com","title":"Cloud Logging API"},{"name":"autoscaling.googleapis.com","title":"Cloud Autoscaling API"},{"name":"cloudtrace.googleapis.com","title":"Cloud Trace API"},{"name":"bigquery.googleapis.com","title":"BigQuery API"},{"name":"clouddebugger.googleapis.com","title":"Cloud Debugger API"},{"name":"cloudasset.googleapis.com","title":"Cloud Asset API"},{"name":"cloudapis.googleapis.com","title":"Google Cloud APIs"},{"name":"compute.googleapis.com","title":"Compute Engine API"},{"name":"serviceusage.googleapis.com","title":"Service Usage API"},{"name":"cloudresourcemanager.googleapis.com","title":"Cloud Resource Manager API"},{"name":"apikeys.googleapis.com","title":"API Keys API"},{"name":"appengine.googleapis.com","title":"App Engine Admin API"},{"name":"bigtableadmin.googleapis.com","title":"Cloud Bigtable Admin API"},{"name":"admin.googleapis.com","title":"Admin SDK API"},{"name":"kmsinventory.googleapis.com","title":"KMS Inventory API"},{"name":"container.googleapis.com","title":"Kubernetes Engine API"},{"name":"sqladmin.googleapis.com","title":"Cloud SQL Admin API"},{"name":"iam.googleapis.com","title":"Identity and Access Management (IAM) API"},{"name":"oslogin.googleapis.com","title":"Cloud OS Login API"},{"name":"bigquerystorage.googleapis.com","title":"BigQuery Storage API"},{"name":"bigtabletableadmin.googleapis.com","title":"Cloud Bigtable Table Admin API"},{"name":"memcache.googleapis.com","title":"Cloud Memorystore for Memcached API"},{"name":"servicenetworking.googleapis.com","title":"Service Networking API"},{"name":"storage-api.googleapis.com","title":"Google Cloud Storage JSON API"},{"name":"cloudfunctions.googleapis.com","title":"Cloud Functions API"},{"name":"storage.googleapis.com","title":"Cloud Storage API"},{"name":"iamcredentials.googleapis.com","title":"IAM Service Account Credentials API"},{"name":"datastore.googleapis.com","title":"Cloud Datastore API"},{"name":"dns.googleapis.com","title":"Cloud DNS API"},{"name":"file.googleapis.com","title":"Cloud Filestore API"},{"name":"storage-component.googleapis.com","title":"Cloud Storage"},{"name":"containerregistry.googleapis.com","title":"Container Registry API"},{"name":"pubsub.googleapis.com","title":"Cloud Pub/Sub API"},{"name":"bigquerymigration.googleapis.com","title":"BigQuery Migration API"},{"name":"containerfilesystem.googleapis.com","title":"Container File System API"},{"name":"source.googleapis.com","title":"Legacy Cloud Source Repositories API"},{"name":"sql-component.googleapis.com","title":"Cloud SQL"},{"name":"deploymentmanager.googleapis.com","title":"Cloud Deployment Manager V2 API"},{"name":"monitoring.googleapis.com","title":"Cloud Monitoring API"},{"name":"servicemanagement.googleapis.com","title":"Service Management API"},{"name":"cloudkms.googleapis.com","title":"Cloud Key Management Service (KMS) API"},{"name":"accessapproval.googleapis.com","title":"Access Approval API"},{"name":"essentialcontacts.googleapis.com","title":"Essential Contacts API"},{"name":"redis.googleapis.com","title":"Google Cloud Memorystore for Redis API"}],"projectNumber":"554880214893","lifecycleState":"ACTIVE","createTime":1686115018,"labels":null,"accessApprovalSettings":null,"selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105","id":"7542766970734488923","type":"Project","name":"serious-conduit-389105","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|ProjectInfo|serious-conduit-389105","accountNumber":"serious-conduit-389105","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/webhook-1686305211924.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"5kc3NtfQv7BuvqrqoWzL5Q","findingId":"5kc3NtfQv7BuvqrqoWzL5Q","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"GCP CloudGuard Best Practices","description":"CloudGuard Best Practices for securing GCP Account","id":-9},"reportTime":"2023-06-09T09:04:54.86Z","rule":{"name":"Ensure 'Access Approval' is 'Enabled'","ruleId":"D9.GCP.LOG.30","description":"GCP Access Approval enables you to require your organizations' explicit approval whenever Google support try to access your projects. You can then select users within your organization who can approve these requests through giving them a security role in IAM. All access requests display which Google Employee requested them in an email or Pub/Sub message that you can choose to Approve. This adds an additional control and logging of who in your organization approved/denied these requests.Controlling access to your information is one of the foundations of information security. Google Employees do have access to your organizations' projects for support reasons. With Access Approval, organizations can then be certain that their information is accessed by only approved Google Personnel.","remediation":"\n**From Portal**\n1. From the Google Cloud Home, within the project you wish to enable, click on the Navigation hamburger menu in the top left. Hover over the Security Menu. Select Access Approval in the middle of the column that opens.\n2. The status will be displayed here. On this screen, there is an option to click Enroll. If it is greyed out and you see an error bar at the top of the screen that says Access Transparency is not enabled please view the corresponding reference within this section to enable it.\n3. In the second screen click Enroll.\n\nA) Grant an IAM Group or User the role with permissions to Add Users to be Access Approval message Recipients\n1. From the Google Cloud Home, within the project you wish to enable, click on the Navigation hamburger menu in the top left. Hover over the IAM and Admin. Select IAM in the middle of the column that opens.\n2. Click the blue button the says +add at the top of the screen.\n3. In the principals field, select a user or group by typing in their associated email address.\n4. Click on the role field to expand it. In the filter field enter Access Approval Approver and select it.\n5. Click save.\n\nB) Add a Group or User as an Approver for Access Approval Requests\n1. As a user with the Access Approval Approver permission, within the project where you wish to add an email address to which request will be sent, click on the Navigation hamburger menu in the top left. Hover over the Security Menu. Select Access Approval in the middle of the column that opens.\n2. Click Manage Settings\n3. Under Set up approval notifications, enter the email address associated with a Google Cloud User or Group you wish to send Access Approval requests to. All future access approvals will be sent as emails to this address.\n\n**From Command Line**\n1. To update all services in an entire project, run the following command from an account that has permissions as an 'Approver for Access Approval Requests'\n```\ngcloud access-approval settings update --project=PROJECT_NAME --enrolled_services=all --notification_emails='exampleuser@example.com'\n```\n2. Determine if Access Approval is Enabled.From within the project you wish to audit, run the following command.\n```\ngcloud access-approval settings get\n```\n\n**FROM TF**\nUse resource google_project_access_approval_settings. Make sure you set the values for arguments as below;\nnotification_emails = [\"testuser@example.com\"]\ncloud_product = \"all\"\n\n```\nresource \"google_project_access_approval_settings\" \"project_access_approval\" {\nproject_id          = \"my-project-name\"\nnotification_emails = [\"testuser@example.com\"]\n\nenrolled_services {\ncloud_product = \"all\"\nenrollment_level = \"BLOCK_ALL\"\n}\n}\n```\n**References**\n1. https://workbench.cisecurity.org/sections/811636/recommendations/1547149\n2. https://cloud.google.com/cloud-provider-access-management/access-approval/docs/overview\n3. https://cloud.google.com/cloud-provider-access-management/access-approval/docs/review-approve-access-requests-custom-keys\n4. https://cloud.google.com/sdk/gcloud/reference/access-approval/settings/update\n5. https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/project_access_approval_settings","complianceTags":"Logging","logicHash":"KwCIwuKpufMfJrXUlbZEgA","severity":"Low"},"account":{"id":"serious-conduit-389105","name":"GCP Demo Account NU","vendor":"GCP","dome9CloudAccountId":"ca5ef528-d8dd-41d8-a022-1a820a6adb60","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"defaultServiceAccount":"554880214893-compute@developer.gserviceaccount.com","description":null,"enabledFeatures":null,"metadata":{"items":null,"eTag":null,"kind":"compute#metadata"},"sharedVpcHostProjectId":null,"enabledServices":[{"name":"logging.googleapis.com","title":"Cloud Logging API"},{"name":"autoscaling.googleapis.com","title":"Cloud Autoscaling API"},{"name":"cloudtrace.googleapis.com","title":"Cloud Trace API"},{"name":"bigquery.googleapis.com","title":"BigQuery API"},{"name":"clouddebugger.googleapis.com","title":"Cloud Debugger API"},{"name":"cloudasset.googleapis.com","title":"Cloud Asset API"},{"name":"cloudapis.googleapis.com","title":"Google Cloud APIs"},{"name":"compute.googleapis.com","title":"Compute Engine API"},{"name":"serviceusage.googleapis.com","title":"Service Usage API"},{"name":"cloudresourcemanager.googleapis.com","title":"Cloud Resource Manager API"},{"name":"apikeys.googleapis.com","title":"API Keys API"},{"name":"appengine.googleapis.com","title":"App Engine Admin API"},{"name":"bigtableadmin.googleapis.com","title":"Cloud Bigtable Admin API"},{"name":"admin.googleapis.com","title":"Admin SDK API"},{"name":"kmsinventory.googleapis.com","title":"KMS Inventory API"},{"name":"container.googleapis.com","title":"Kubernetes Engine API"},{"name":"sqladmin.googleapis.com","title":"Cloud SQL Admin API"},{"name":"iam.googleapis.com","title":"Identity and Access Management (IAM) API"},{"name":"oslogin.googleapis.com","title":"Cloud OS Login API"},{"name":"bigquerystorage.googleapis.com","title":"BigQuery Storage API"},{"name":"bigtabletableadmin.googleapis.com","title":"Cloud Bigtable Table Admin API"},{"name":"memcache.googleapis.com","title":"Cloud Memorystore for Memcached API"},{"name":"servicenetworking.googleapis.com","title":"Service Networking API"},{"name":"storage-api.googleapis.com","title":"Google Cloud Storage JSON API"},{"name":"cloudfunctions.googleapis.com","title":"Cloud Functions API"},{"name":"storage.googleapis.com","title":"Cloud Storage API"},{"name":"iamcredentials.googleapis.com","title":"IAM Service Account Credentials API"},{"name":"datastore.googleapis.com","title":"Cloud Datastore API"},{"name":"dns.googleapis.com","title":"Cloud DNS API"},{"name":"file.googleapis.com","title":"Cloud Filestore API"},{"name":"storage-component.googleapis.com","title":"Cloud Storage"},{"name":"containerregistry.googleapis.com","title":"Container Registry API"},{"name":"pubsub.googleapis.com","title":"Cloud Pub/Sub API"},{"name":"bigquerymigration.googleapis.com","title":"BigQuery Migration API"},{"name":"containerfilesystem.googleapis.com","title":"Container File System API"},{"name":"source.googleapis.com","title":"Legacy Cloud Source Repositories API"},{"name":"sql-component.googleapis.com","title":"Cloud SQL"},{"name":"deploymentmanager.googleapis.com","title":"Cloud Deployment Manager V2 API"},{"name":"monitoring.googleapis.com","title":"Cloud Monitoring API"},{"name":"servicemanagement.googleapis.com","title":"Service Management API"},{"name":"cloudkms.googleapis.com","title":"Cloud Key Management Service (KMS) API"},{"name":"accessapproval.googleapis.com","title":"Access Approval API"},{"name":"essentialcontacts.googleapis.com","title":"Essential Contacts API"},{"name":"redis.googleapis.com","title":"Google Cloud Memorystore for Redis API"}],"projectNumber":"554880214893","lifecycleState":"ACTIVE","createTime":1686115018,"labels":null,"accessApprovalSettings":null,"selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105","id":"7542766970734488923","type":"Project","name":"serious-conduit-389105","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|ProjectInfo|serious-conduit-389105","accountNumber":"serious-conduit-389105","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}
