=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_25/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "status": {
            "type": "string"
        },
        "policy": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "description",
                "name"
            ]
        },
        "findingKey": {
            "type": "string"
        },
        "findingId": {
            "type": "string"
        },
        "cloudGuardAccountId": {
            "type": "string"
        },
        "origin": {
            "type": "string"
        },
        "bundle": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            },
            "required": [
                "description",
                "id",
                "name"
            ]
        },
        "reportTime": {
            "type": "string"
        },
        "rule": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "ruleId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "remediation": {
                    "type": "string"
                },
                "complianceTags": {
                    "type": "string"
                },
                "logicHash": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                }
            },
            "required": [
                "complianceTags",
                "description",
                "logicHash",
                "name",
                "remediation",
                "ruleId",
                "severity"
            ]
        },
        "account": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                },
                "dome9CloudAccountId": {
                    "type": "string"
                },
                "organizationalUnitId": {
                    "type": "string"
                },
                "organizationalUnitPath": {
                    "type": "string"
                }
            },
            "required": [
                "dome9CloudAccountId",
                "id",
                "name",
                "organizationalUnitId",
                "organizationalUnitPath",
                "vendor"
            ]
        },
        "region": {
            "type": "string"
        },
        "entity": {
            "type": "object",
            "properties": {
                "acl": {
                    "type": "null"
                },
                "defaultObjectAcl": {
                    "type": "null"
                },
                "location": {
                    "type": "string"
                },
                "logging": {
                    "type": "null"
                },
                "metageneration": {
                    "type": "integer"
                },
                "owner": {
                    "type": "null"
                },
                "projectNumber": {
                    "type": "integer"
                },
                "storageClass": {
                    "type": "string"
                },
                "timeCreatedRaw": {
                    "type": "string"
                },
                "timeCreated": {
                    "type": "integer"
                },
                "updatedRaw": {
                    "type": "string"
                },
                "updated": {
                    "type": "integer"
                },
                "iamPolicy": {
                    "type": "object",
                    "properties": {
                        "bindings": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "members": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    },
                                    "role": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "members",
                                    "role"
                                ]
                            }
                        },
                        "eTag": {
                            "type": "string"
                        },
                        "kind": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "bindings",
                        "eTag",
                        "kind"
                    ]
                },
                "defaultEventBasedHold": {
                    "type": "null"
                },
                "iamConfiguration": {
                    "type": "object",
                    "properties": {
                        "bucketPolicyOnly": {
                            "type": "object",
                            "properties": {
                                "enabled": {
                                    "type": "boolean"
                                },
                                "lockedTimeRaw": {
                                    "type": "string"
                                },
                                "lockedTime": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "enabled",
                                "lockedTime",
                                "lockedTimeRaw"
                            ]
                        },
                        "uniformBucketLevelAccess": {
                            "type": "object",
                            "properties": {
                                "enabled": {
                                    "type": "boolean"
                                },
                                "lockedTimeRaw": {
                                    "type": "string"
                                },
                                "lockedTime": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "enabled",
                                "lockedTime",
                                "lockedTimeRaw"
                            ]
                        },
                        "publicAccessPrevention": {
                            "type": "null"
                        }
                    },
                    "required": [
                        "bucketPolicyOnly",
                        "publicAccessPrevention",
                        "uniformBucketLevelAccess"
                    ]
                },
                "retentionPolicy": {
                    "type": "null"
                },
                "locationType": {
                    "type": "null"
                },
                "customPlacementConfig": {
                    "type": "null"
                },
                "satisfiesPZS": {
                    "type": "null"
                },
                "rpo": {
                    "type": "null"
                },
                "selfLink": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "dome9Id": {
                    "type": "string"
                },
                "accountNumber": {
                    "type": "string"
                },
                "assetLabels": {
                    "type": "null"
                },
                "region": {
                    "type": "string"
                },
                "externalFindings": {
                    "type": "null"
                }
            },
            "required": [
                "accountNumber",
                "acl",
                "assetLabels",
                "customPlacementConfig",
                "defaultEventBasedHold",
                "defaultObjectAcl",
                "dome9Id",
                "externalFindings",
                "iamConfiguration",
                "iamPolicy",
                "id",
                "location",
                "locationType",
                "logging",
                "metageneration",
                "name",
                "owner",
                "projectNumber",
                "region",
                "retentionPolicy",
                "rpo",
                "satisfiesPZS",
                "selfLink",
                "storageClass",
                "timeCreated",
                "timeCreatedRaw",
                "type",
                "updated",
                "updatedRaw"
            ]
        },
        "remediationActions": {
            "type": "array"
        },
        "action": {
            "type": "string"
        },
        "additionalFields": {
            "type": "array"
        }
    },
    "required": [
        "account",
        "action",
        "additionalFields",
        "bundle",
        "cloudGuardAccountId",
        "entity",
        "findingId",
        "findingKey",
        "origin",
        "policy",
        "region",
        "remediationActions",
        "reportTime",
        "rule",
        "status"
    ]
}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_25/webhook-1686305247882.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"A2q02P/SjX1INcT7gaNg6w","findingId":"A2q02P/SjX1INcT7gaNg6w","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"GCP CloudGuard Best Practices","description":"CloudGuard Best Practices for securing GCP Account","id":-9},"reportTime":"2023-06-09T10:06:38.111Z","rule":{"name":"Ensure that Cloud Storage bucket has usage logs enabled","ruleId":"D9.GCP.LOG.01","description":"Turn on usage logs on your Storage Bucket in order to log access of users to public resources, and follow changes with to Object Lifecycle Management feature. Other actions are logged with Cloud Audit Logs, which has to be enabled as well.","remediation":"\n**From Command Line**\nIn order to enable usage logs you should:\n1. Create a bucket to store the logs:\n```\ngsutil mb gs://Bucket_for_logs_storing\n```\n2. Grant it with 'roles/storage.legacyBucketWriter' permissions:\n```\ngsutil iam ch group:cloud-storage-analytics@google.com:legacyBucketWriter gs://<Bucket for logs storing>\n```\n3. Enable usage logging to your desired logs:\n```\ngsutil logging set on -b gs://<Bucket for logs storing> gs://<Bucket to log>\n```\n\n**References**\n1. https://cloud.google.com/storage/docs/gsutil/commands/mb\n2. https://cloud.google.com/storage/docs/gsutil/commands/iam\n3. https://cloud.google.com/storage/docs/gsutil/commands/logging\n4. https://cloud.google.com/storage/docs/access-logs","complianceTags":"Logging","logicHash":"zc2ibp/ZUCkzWPBR5tUhkg","severity":"Low"},"account":{"id":"serious-conduit-389105","name":"GCP Demo Account NU","vendor":"GCP","dome9CloudAccountId":"ca5ef528-d8dd-41d8-a022-1a820a6adb60","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"US-CENTRAL1","entity":{"acl":null,"defaultObjectAcl":null,"location":"US-CENTRAL1","logging":null,"metageneration":1,"owner":null,"projectNumber":554880214893,"storageClass":"STANDARD","timeCreatedRaw":"2023-06-09T09:54:22.796Z","timeCreated":1686304462,"updatedRaw":"2023-06-09T09:54:22.796Z","updated":1686304462,"iamPolicy":{"bindings":[{"members":["projectEditor:serious-conduit-389105","projectOwner:serious-conduit-389105"],"role":"roles/storage.legacyBucketOwner"},{"members":["projectViewer:serious-conduit-389105"],"role":"roles/storage.legacyBucketReader"},{"members":["projectEditor:serious-conduit-389105","projectOwner:serious-conduit-389105"],"role":"roles/storage.legacyObjectOwner"},{"members":["projectViewer:serious-conduit-389105"],"role":"roles/storage.legacyObjectReader"}],"eTag":"CAE=","kind":"storage#policy"},"defaultEventBasedHold":null,"iamConfiguration":{"bucketPolicyOnly":{"enabled":true,"lockedTimeRaw":"2023-09-07T09:54:22.796Z","lockedTime":"2023-09-07T09:54:22.796Z"},"uniformBucketLevelAccess":{"enabled":true,"lockedTimeRaw":"2023-09-07T09:54:22.796Z","lockedTime":"2023-09-07T09:54:22.796Z"},"publicAccessPrevention":null},"retentionPolicy":null,"locationType":null,"customPlacementConfig":null,"satisfiesPZS":null,"rpo":null,"selfLink":"https://www.googleapis.com/storage/v1/b/gcf-sources-554880214893-us-central1","id":"gcf-sources-554880214893-us-central1","type":"StorageBucket","name":"gcf-sources-554880214893-us-central1","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|StorageBucket|gcf-sources-554880214893-us-central1","accountNumber":"serious-conduit-389105","assetLabels":null,"region":"US-CENTRAL1","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}
