=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_1/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "status": {
            "type": "string"
        },
        "policy": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "description",
                "name"
            ]
        },
        "findingKey": {
            "type": "string"
        },
        "findingId": {
            "type": "string"
        },
        "cloudGuardAccountId": {
            "type": "string"
        },
        "origin": {
            "type": "string"
        },
        "bundle": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            },
            "required": [
                "description",
                "id",
                "name"
            ]
        },
        "reportTime": {
            "type": "string"
        },
        "rule": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "ruleId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "remediation": {
                    "type": "string"
                },
                "complianceTags": {
                    "type": "string"
                },
                "logicHash": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                }
            },
            "required": [
                "complianceTags",
                "description",
                "logicHash",
                "name",
                "remediation",
                "ruleId",
                "severity"
            ]
        },
        "account": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                },
                "dome9CloudAccountId": {
                    "type": "string"
                },
                "organizationalUnitId": {
                    "type": "string"
                },
                "organizationalUnitPath": {
                    "type": "string"
                }
            },
            "required": [
                "dome9CloudAccountId",
                "id",
                "name",
                "organizationalUnitId",
                "organizationalUnitPath",
                "vendor"
            ]
        },
        "region": {
            "type": "string"
        },
        "entity": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "null"
                },
                "gatewayAddress": {
                    "type": "string"
                },
                "ipCidrRange": {
                    "type": "string"
                },
                "network": {
                    "type": "string"
                },
                "networkData": {
                    "type": "object",
                    "properties": {
                        "autoCreateSubnetworks": {
                            "type": "boolean"
                        },
                        "description": {
                            "type": "string"
                        },
                        "gatewayIPv4": {
                            "type": "null"
                        },
                        "iPv4Range": {
                            "type": "null"
                        },
                        "name": {
                            "type": "string"
                        },
                        "dome9Id": {
                            "type": "string"
                        },
                        "selfLink": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "autoCreateSubnetworks",
                        "description",
                        "dome9Id",
                        "gatewayIPv4",
                        "iPv4Range",
                        "name",
                        "selfLink"
                    ]
                },
                "fingerPrint": {
                    "type": "string"
                },
                "allowSubnetCidrRoutesOverlap": {
                    "type": "boolean"
                },
                "enableFlowLogs": {
                    "type": "null"
                },
                "privateIpGoogleAccess": {
                    "type": "boolean"
                },
                "secondaryIpRanges": {
                    "type": "array"
                },
                "resourceType": {
                    "type": "string"
                },
                "selfLink": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "dome9Id": {
                    "type": "string"
                },
                "accountNumber": {
                    "type": "string"
                },
                "assetLabels": {
                    "type": "null"
                },
                "region": {
                    "type": "string"
                },
                "externalFindings": {
                    "type": "null"
                }
            },
            "required": [
                "accountNumber",
                "allowSubnetCidrRoutesOverlap",
                "assetLabels",
                "description",
                "dome9Id",
                "enableFlowLogs",
                "externalFindings",
                "fingerPrint",
                "gatewayAddress",
                "id",
                "ipCidrRange",
                "name",
                "network",
                "networkData",
                "privateIpGoogleAccess",
                "region",
                "resourceType",
                "secondaryIpRanges",
                "selfLink",
                "type"
            ]
        },
        "remediationActions": {
            "type": "array"
        },
        "action": {
            "type": "string"
        },
        "additionalFields": {
            "type": "array"
        }
    },
    "required": [
        "account",
        "action",
        "additionalFields",
        "bundle",
        "cloudGuardAccountId",
        "entity",
        "findingId",
        "findingKey",
        "origin",
        "policy",
        "region",
        "remediationActions",
        "reportTime",
        "rule",
        "status"
    ]
}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/webhook-1686305240049.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"sTiusnmJHuq37FPhDvO0WQ","findingId":"sTiusnmJHuq37FPhDvO0WQ","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"GCP CloudGuard Best Practices","description":"CloudGuard Best Practices for securing GCP Account","id":-9},"reportTime":"2023-06-09T09:04:54.86Z","rule":{"name":"Ensure Private Google Access is enabled for all subnetworks in VPC Network","ruleId":"D9.GCP.NET.14","description":"Private Google Access enables virtual machine instances on a subnet to reach Google APIs and services using an internal IP address rather than an external IP address. External IP addresses are routable and reachable over the Internet. Internal (private) IP addresses are internal to Google Cloud Platform and are not routable or reachable over the Internet. You can use Private Google Access to allow VMs without Internet access to reach Google APIs, services, and properties that are accessible over HTTP/HTTPS.","remediation":"\n**From Portal**\n1. Go to VPC network GCP Console visiting https://console.cloud.google.com/networking/networks/list\n2. Click the name of the network that contains the subnet.\n3. Click the name of the subnet. The Subnet details page is displayed.\n4. Click on EDIT button\n5. Set Private Google access to On\n6. Click on Save\n\n**From TF**\nSet the private_ip_google_access argument to 'true':\n```\nresource \"google_compute_subnetwork\" \"container_subnetwork\" {\n...\nprivate_ip_google_access = true\n...\n}\n```\n\n**From Command Line**\nRun\n```\ngcloud compute networks subnets update SUBNET_NAME --region=REGION --enable-private-ip-google-access\n```\n\n**References**\n1. https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_subnetwork\n2. https://cloud.google.com/vpc/docs/configure-private-google-access\n\n","complianceTags":"Network Security","logicHash":"Dxck6J+NBk0PWgpDEvfRLA","severity":"High"},"account":{"id":"serious-conduit-389105","name":"GCP Demo Account NU","vendor":"GCP","dome9CloudAccountId":"ca5ef528-d8dd-41d8-a022-1a820a6adb60","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"northamerica-northeast2","entity":{"description":null,"gatewayAddress":"10.188.0.1","ipCidrRange":"10.188.0.0/20","network":"default","networkData":{"autoCreateSubnetworks":true,"description":"Default network for the project","gatewayIPv4":null,"iPv4Range":null,"name":"default","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|Network|default","selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105/global/networks/default"},"fingerPrint":"pOH0fyylKJY=","allowSubnetCidrRoutesOverlap":false,"enableFlowLogs":null,"privateIpGoogleAccess":false,"secondaryIpRanges":[],"resourceType":"Local","selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105/regions/northamerica-northeast2/subnetworks/default","id":"3838136276665347370","type":"Subnet","name":"default","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|Region|northamerica-northeast2|Subnet|default","accountNumber":"serious-conduit-389105","assetLabels":null,"region":"northamerica-northeast2","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/webhook-1686305233206.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"mr+WGKbNWd7GQGXgpvfNCw","findingId":"mr+WGKbNWd7GQGXgpvfNCw","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"GCP CloudGuard Best Practices","description":"CloudGuard Best Practices for securing GCP Account","id":-9},"reportTime":"2023-06-09T09:04:54.86Z","rule":{"name":"Ensure VPC Flow logs is enabled for every subnet in a VPC Network","ruleId":"D9.GCP.NET.16","description":"Flow Logs is a feature that enables you to capture information about the IP traffic going to\nand from network interfaces in your VPC Subnets. After you've created a flow log, you can\nview and retrieve its data in Stackdriver Logging. It is recommended that Flow Logs be\nenabled for every business critical VPC subnet.\nFlow Logs provide visibility into network traffic for each VM inside the subnet and can be\nused to detect anomalous traffic or insight during security workflows.","remediation":"\n**From Portal**\n1. Go to VPC network GCP Console visiting https://console.cloud.google.com/networking/networks/list\n2. Click the name of a subnet, The Subnet details page is displayed\n3. Click on EDIT button\n4. Set Flow Logs to On\n5. Expand the Configure Logs section.\n6. Set Aggregation Interval to 5 SEC.\n7. Check the box beside Include metadata.\n8. Set Sample rate to 100.\n9. Click Save.\n\n\n**From TF**\n```\nresource 'google_compute_subnetwork' 'subnetwork' {\n\nlog_config {\naggregation_interval = 'INTERVAL_10_MIN'\nflow_sampling        = 0.5\nmetadata             = 'INCLUDE_ALL_METADATA'\n}\n}\n```\n\n**From Command Line**\nRun\n```\ngcloud compute networks subnets update [SUBNET_NAME] --region [REGION] --enable-flow-logs --logging-aggregation-interval=interval-5-sec --logging-flow-sampling=1 --logging-metadata=include-all\n\n```\n\n**References**\n1. https://cloud.google.com/vpc/docs/using-flow-logs#enabling_vpc_flow_logging\n2. https://cloud.google.com/vpc/\n","complianceTags":"Network Security","logicHash":"iPJ1kGZzQt8svkXFtJFHyg","severity":"Medium"},"account":{"id":"serious-conduit-389105","name":"GCP Demo Account NU","vendor":"GCP","dome9CloudAccountId":"ca5ef528-d8dd-41d8-a022-1a820a6adb60","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"europe-west3","entity":{"description":null,"gatewayAddress":"10.156.0.1","ipCidrRange":"10.156.0.0/20","network":"default","networkData":{"autoCreateSubnetworks":true,"description":"Default network for the project","gatewayIPv4":null,"iPv4Range":null,"name":"default","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|Network|default","selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105/global/networks/default"},"fingerPrint":"zlc19BjUvKE=","allowSubnetCidrRoutesOverlap":false,"enableFlowLogs":null,"privateIpGoogleAccess":false,"secondaryIpRanges":[],"resourceType":"Local","selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105/regions/europe-west3/subnetworks/default","id":"7037095826454064426","type":"Subnet","name":"default","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|Region|europe-west3|Subnet|default","accountNumber":"serious-conduit-389105","assetLabels":null,"region":"europe-west3","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}
