=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_45/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "status": {
            "type": "string"
        },
        "policy": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "description",
                "name"
            ]
        },
        "findingKey": {
            "type": "string"
        },
        "findingId": {
            "type": "string"
        },
        "cloudGuardAccountId": {
            "type": "string"
        },
        "origin": {
            "type": "string"
        },
        "bundle": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            },
            "required": [
                "description",
                "id",
                "name"
            ]
        },
        "reportTime": {
            "type": "string"
        },
        "rule": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "ruleId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "remediation": {
                    "type": "string"
                },
                "complianceTags": {
                    "type": "string"
                },
                "logicHash": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                }
            },
            "required": [
                "complianceTags",
                "description",
                "logicHash",
                "name",
                "remediation",
                "ruleId",
                "severity"
            ]
        },
        "account": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                },
                "dome9CloudAccountId": {
                    "type": "string"
                },
                "organizationalUnitId": {
                    "type": "string"
                },
                "organizationalUnitPath": {
                    "type": "string"
                }
            },
            "required": [
                "dome9CloudAccountId",
                "id",
                "name",
                "organizationalUnitId",
                "organizationalUnitPath",
                "vendor"
            ]
        },
        "region": {
            "type": "string"
        },
        "entity": {
            "type": "object",
            "properties": {
                "automountServiceAccountToken": {
                    "type": "boolean"
                },
                "imagePullSecrets": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name"
                        ]
                    }
                },
                "secrets": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "apiVersion": {
                                "type": "null"
                            },
                            "fieldPath": {
                                "type": "null"
                            },
                            "name": {
                                "type": "string"
                            },
                            "namespace": {
                                "type": "null"
                            },
                            "resourceVersion": {
                                "type": "null"
                            },
                            "uid": {
                                "type": "null"
                            }
                        },
                        "required": [
                            "apiVersion",
                            "fieldPath",
                            "name",
                            "namespace",
                            "resourceVersion",
                            "uid"
                        ]
                    }
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "key": {
                                "type": "string"
                            },
                            "value": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "key",
                            "value"
                        ]
                    }
                },
                "namespace": {
                    "type": "string"
                },
                "annotations": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "key": {
                                "type": "string"
                            },
                            "value": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "key",
                            "value"
                        ]
                    }
                },
                "labels": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "key": {
                                "type": "string"
                            },
                            "value": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "key",
                            "value"
                        ]
                    }
                },
                "creationTime": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "dome9Id": {
                    "type": "string"
                },
                "accountNumber": {
                    "type": "string"
                },
                "assetLabels": {
                    "type": "null"
                },
                "region": {
                    "type": "string"
                },
                "externalFindings": {
                    "type": "null"
                }
            },
            "required": [
                "accountNumber",
                "annotations",
                "assetLabels",
                "automountServiceAccountToken",
                "creationTime",
                "dome9Id",
                "externalFindings",
                "id",
                "imagePullSecrets",
                "labels",
                "name",
                "namespace",
                "region",
                "secrets",
                "tags",
                "type"
            ]
        },
        "remediationActions": {
            "type": "array"
        },
        "action": {
            "type": "string"
        },
        "additionalFields": {
            "type": "array"
        }
    },
    "required": [
        "account",
        "action",
        "additionalFields",
        "bundle",
        "cloudGuardAccountId",
        "entity",
        "findingId",
        "findingKey",
        "origin",
        "policy",
        "region",
        "remediationActions",
        "reportTime",
        "rule",
        "status"
    ]
}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_45/webhook-1686308577684.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"u1mTfnUgAbWZc4FRA8l9pA","findingId":"u1mTfnUgAbWZc4FRA8l9pA","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"CIS Kubernetes Benchmark v1.6.1","description":"Automated Validation of Kubernetes CIS Benchmark v1.6.1 Prescriptive guidance for establishing a secure configuration posture for Kubernetes 1.6.1\nFor additional reference: https://www.cisecurity.org/benchmark/kubernetes/","id":-70},"reportTime":"2023-06-09T11:00:31.243Z","rule":{"name":"Ensure that Service Account Tokens are only mounted where necessary (RBAC)","ruleId":"D9.K8S.IAM.37","description":"Service accounts tokens should not be mounted in pods except where the workload running in the pod explicitly needs to communicate with the API server. Mounting service account tokens inside pods can provide an avenue for privilege escalation attacks where an attacker is able to compromise a single pod in the cluster. Avoiding mounting these tokens removes this attack avenue.","remediation":"Modify the definition of pods and service accounts which do not need to mount service account tokens to disable it.\n\n**References**\n1. https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/","complianceTags":"5.1.6","logicHash":"cSTcHpdCLI84ZSeS/rDcxQ","severity":"Low"},"account":{"id":"5af13ab5-72ed-43b6-9544-33c9236d62f0","name":"nu-openshift-cluster","vendor":"Kubernetes","dome9CloudAccountId":"5af13ab5-72ed-43b6-9544-33c9236d62f0","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"automountServiceAccountToken":true,"imagePullSecrets":[{"name":"my-harbor-redis-dockercfg-q4tmx"}],"secrets":[{"apiVersion":null,"fieldPath":null,"name":"my-harbor-redis-dockercfg-q4tmx","namespace":null,"resourceVersion":null,"uid":null}],"tags":[{"key":"app.kubernetes.io/instance","value":"my-harbor"},{"key":"app.kubernetes.io/managed-by","value":"Helm"},{"key":"app.kubernetes.io/name","value":"redis"},{"key":"helm.sh/chart","value":"redis-17.4.2"}],"namespace":"harbor","annotations":[{"key":"meta.helm.sh/release-name","value":"my-harbor"},{"key":"meta.helm.sh/release-namespace","value":"harbor"}],"labels":[{"key":"app.kubernetes.io/instance","value":"my-harbor"},{"key":"app.kubernetes.io/managed-by","value":"Helm"},{"key":"app.kubernetes.io/name","value":"redis"},{"key":"helm.sh/chart","value":"redis-17.4.2"}],"creationTime":1676446442,"id":"f73ee6a0-d0e8-4fa3-9c0b-43ceff4f129e","type":"KubernetesServiceAccount","name":"my-harbor-redis","dome9Id":"11|5af13ab5-72ed-43b6-9544-33c9236d62f0|ServiceAccount|f73ee6a0-d0e8-4fa3-9c0b-43ceff4f129e","accountNumber":"5af13ab5-72ed-43b6-9544-33c9236d62f0","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}
