=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_9/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "status": {
            "type": "string"
        },
        "policy": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "description",
                "name"
            ]
        },
        "findingKey": {
            "type": "string"
        },
        "findingId": {
            "type": "string"
        },
        "cloudGuardAccountId": {
            "type": "string"
        },
        "origin": {
            "type": "string"
        },
        "bundle": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            },
            "required": [
                "description",
                "id",
                "name"
            ]
        },
        "reportTime": {
            "type": "string"
        },
        "rule": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "ruleId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "remediation": {
                    "type": "string"
                },
                "complianceTags": {
                    "type": "string"
                },
                "logicHash": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                }
            },
            "required": [
                "complianceTags",
                "description",
                "logicHash",
                "name",
                "remediation",
                "ruleId",
                "severity"
            ]
        },
        "account": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                },
                "dome9CloudAccountId": {
                    "type": "string"
                },
                "organizationalUnitId": {
                    "type": "string"
                },
                "organizationalUnitPath": {
                    "type": "string"
                }
            },
            "required": [
                "dome9CloudAccountId",
                "id",
                "name",
                "organizationalUnitId",
                "organizationalUnitPath",
                "vendor"
            ]
        },
        "region": {
            "type": "string"
        },
        "entity": {
            "type": "object",
            "properties": {
                "autoCreateSubnetworks": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "gatewayIPv4": {
                    "type": "null"
                },
                "iPv4Range": {
                    "type": "null"
                },
                "subnetworks": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "description": {
                                "type": "null"
                            },
                            "gatewayAddress": {
                                "type": "string"
                            },
                            "ipCidrRange": {
                                "type": "string"
                            },
                            "network": {
                                "type": "string"
                            },
                            "fingerPrint": {
                                "type": "string"
                            },
                            "allowSubnetCidrRoutesOverlap": {
                                "type": "boolean"
                            },
                            "enableFlowLogs": {
                                "type": "null"
                            },
                            "privateIpGoogleAccess": {
                                "type": "boolean"
                            },
                            "secondaryIpRanges": {
                                "type": "array"
                            },
                            "name": {
                                "type": "string"
                            },
                            "dome9Id": {
                                "type": "string"
                            },
                            "region": {
                                "type": "string"
                            },
                            "selfLink": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "allowSubnetCidrRoutesOverlap",
                            "description",
                            "dome9Id",
                            "enableFlowLogs",
                            "fingerPrint",
                            "gatewayAddress",
                            "ipCidrRange",
                            "name",
                            "network",
                            "privateIpGoogleAccess",
                            "region",
                            "secondaryIpRanges",
                            "selfLink"
                        ]
                    }
                },
                "firewallRules": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "allowed": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "ipProtocol": {
                                            "type": "string"
                                        },
                                        "ports": {
                                            "anyOf": [
                                                {
                                                    "type": "null"
                                                },
                                                {
                                                    "type": "array",
                                                    "items": {
                                                        "type": "string"
                                                    }
                                                }
                                            ]
                                        }
                                    },
                                    "required": [
                                        "ipProtocol",
                                        "ports"
                                    ]
                                }
                            },
                            "denied": {
                                "type": "null"
                            },
                            "description": {
                                "type": "string"
                            },
                            "destinationRanges": {
                                "type": "null"
                            },
                            "network": {
                                "type": "string"
                            },
                            "sourceRanges": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "sourceTags": {
                                "type": "null"
                            },
                            "targetTags": {
                                "type": "null"
                            },
                            "priority": {
                                "type": "integer"
                            },
                            "direction": {
                                "type": "string"
                            },
                            "action": {
                                "type": "string"
                            },
                            "enabled": {
                                "type": "boolean"
                            },
                            "logConfig": {
                                "type": "object",
                                "properties": {
                                    "enable": {
                                        "type": "boolean"
                                    },
                                    "eTag": {
                                        "type": "null"
                                    }
                                },
                                "required": [
                                    "eTag",
                                    "enable"
                                ]
                            },
                            "enableLogging": {
                                "type": "boolean"
                            },
                            "targetServiceAccounts": {
                                "type": "null"
                            },
                            "sourceServiceAccounts": {
                                "type": "null"
                            }
                        },
                        "required": [
                            "action",
                            "allowed",
                            "denied",
                            "description",
                            "destinationRanges",
                            "direction",
                            "enableLogging",
                            "enabled",
                            "logConfig",
                            "network",
                            "priority",
                            "sourceRanges",
                            "sourceServiceAccounts",
                            "sourceTags",
                            "targetServiceAccounts",
                            "targetTags"
                        ]
                    }
                },
                "resourceType": {
                    "type": "string"
                },
                "dnsPolicy": {
                    "type": "null"
                },
                "isLegacy": {
                    "type": "boolean"
                },
                "selfLink": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "dome9Id": {
                    "type": "string"
                },
                "accountNumber": {
                    "type": "string"
                },
                "assetLabels": {
                    "type": "null"
                },
                "region": {
                    "type": "string"
                },
                "externalFindings": {
                    "type": "null"
                }
            },
            "required": [
                "accountNumber",
                "assetLabels",
                "autoCreateSubnetworks",
                "description",
                "dnsPolicy",
                "dome9Id",
                "externalFindings",
                "firewallRules",
                "gatewayIPv4",
                "iPv4Range",
                "id",
                "isLegacy",
                "name",
                "region",
                "resourceType",
                "selfLink",
                "subnetworks",
                "type"
            ]
        },
        "remediationActions": {
            "type": "array"
        },
        "action": {
            "type": "string"
        },
        "additionalFields": {
            "type": "array"
        }
    },
    "required": [
        "account",
        "action",
        "additionalFields",
        "bundle",
        "cloudGuardAccountId",
        "entity",
        "findingId",
        "findingKey",
        "origin",
        "policy",
        "region",
        "remediationActions",
        "reportTime",
        "rule",
        "status"
    ]
}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/webhook-1686305241321.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"tT5RPDNUjHXQNf6d1fsMbA","findingId":"tT5RPDNUjHXQNf6d1fsMbA","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"GCP CloudGuard Best Practices","description":"CloudGuard Best Practices for securing GCP Account","id":-9},"reportTime":"2023-06-09T09:04:54.86Z","rule":{"name":"Ensure the default network does not exist in a project","ruleId":"D9.GCP.NET.20","description":"The default network has automatically created firewall rules and has default configurations. It is recommended to create your network and delete the default network.","remediation":"\n**From Portal**\n1. Go to VPC networks https://console.cloud.google.com/networking/networks\n2. Click the network named 'default'\n3. Click DELETE VPC NETWORK\n\n\n**From TF**\nSet the auto_create_network to be equal to false:\n```\nresource 'google_project' 'my_project' {\n...\nauto_create_network   = false\n...\n}\n\n```\n\n**From Command Line**\nRun\n```\ngcloud compute networks delete default\n```\n\n**References**\n1. https://cloud.google.com/compute/docs/networking#firewall_rules\n2. https://cloud.google.com/compute/docs/reference/latest/networks/insert\n3. https://cloud.google.com/compute/docs/reference/latest/networks/delete\n","complianceTags":"Network Security","logicHash":"f6T4YF+1KDEsvEd7qXprIA","severity":"Medium"},"account":{"id":"serious-conduit-389105","name":"GCP Demo Account NU","vendor":"GCP","dome9CloudAccountId":"ca5ef528-d8dd-41d8-a022-1a820a6adb60","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"autoCreateSubnetworks":true,"description":"Default network for the project","gatewayIPv4":null,"iPv4Range":null,"subnetworks":[{"description":null,"gatewayAddress":"10.128.0.1","ipCidrRange":"10.128.0.0/20","network":"default","fingerPrint":"TEpAg1tAOJU=","allowSubnetCidrRoutesOverlap":false,"enableFlowLogs":null,"privateIpGoogleAccess":false,"secondaryIpRanges":[],"name":"default","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|Region|us-central1|Subnet|default","region":"us-central1","selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105/regions/us-central1/subnetworks/default"},{"description":null,"gatewayAddress":"10.132.0.1","ipCidrRange":"10.132.0.0/20","network":"default","fingerPrint":"7Nqg_4Lkkc0=","allowSubnetCidrRoutesOverlap":false,"enableFlowLogs":null,"privateIpGoogleAccess":false,"secondaryIpRanges":[],"name":"default","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|Region|europe-west1|Subnet|default","region":"europe-west1","selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105/regions/europe-west1/subnetworks/default"},{"description":null,"gatewayAddress":"10.138.0.1","ipCidrRange":"10.138.0.0/20","network":"default","fingerPrint":"NEer0Zop4yk=","allowSubnetCidrRoutesOverlap":false,"enableFlowLogs":null,"privateIpGoogleAccess":false,"secondaryIpRanges":[],"name":"default","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|Region|us-west1|Subnet|default","region":"us-west1","selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105/regions/us-west1/subnetworks/default"},{"description":null,"gatewayAddress":"10.140.0.1","ipCidrRange":"10.140.0.0/20","network":"default","fingerPrint":"Q44f3tBE-to=","allowSubnetCidrRoutesOverlap":false,"enableFlowLogs":null,"privateIpGoogleAccess":false,"secondaryIpRanges":[],"name":"default","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|Region|asia-east1|Subnet|default","region":"asia-east1","selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105/regions/asia-east1/subnetworks/default"},{"description":null,"gatewayAddress":"10.142.0.1","ipCidrRange":"10.142.0.0/20","network":"default","fingerPrint":"VwwhnK5et7I=","allowSubnetCidrRoutesOverlap":false,"enableFlowLogs":null,"privateIpGoogleAccess":false,"secondaryIpRanges":[],"name":"default","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|Region|us-east1|Subnet|default","region":"us-east1","selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105/regions/us-east1/subnetworks/default"},{"description":null,"gatewayAddress":"10.146.0.1","ipCidrRange":"10.146.0.0/20","network":"default","fingerPrint":"jLOA0ZQ_UZY=","allowSubnetCidrRoutesOverlap":false,"enableFlowLogs":null,"privateIpGoogleAccess":false,"secondaryIpRanges":[],"name":"default","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|Region|asia-northeast1|Subnet|default","region":"asia-northeast1","selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105/regions/asia-northeast1/subnetworks/default"},{"description":null,"gatewayAddress":"10.148.0.1","ipCidrRange":"10.148.0.0/20","network":"default","fingerPrint":"3E44cc5a5p4=","allowSubnetCidrRoutesOverlap":false,"enableFlowLogs":null,"privateIpGoogleAccess":false,"secondaryIpRanges":[],"name":"default","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|Region|asia-southeast1|Subnet|default","region":"asia-southeast1","selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105/regions/asia-southeast1/subnetworks/default"},{"description":null,"gatewayAddress":"10.150.0.1","ipCidrRange":"10.150.0.0/20","network":"default","fingerPrint":"tF3Sm9OrUc0=","allowSubnetCidrRoutesOverlap":false,"enableFlowLogs":null,"privateIpGoogleAccess":false,"secondaryIpRanges":[],"name":"default","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|Region|us-east4|Subnet|default","region":"us-east4","selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105/regions/us-east4/subnetworks/default"},{"description":null,"gatewayAddress":"10.152.0.1","ipCidrRange":"10.152.0.0/20","network":"default","fingerPrint":"y0qZwVwsIR8=","allowSubnetCidrRoutesOverlap":false,"enableFlowLogs":null,"privateIpGoogleAccess":false,"secondaryIpRanges":[],"name":"default","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|Region|australia-southeast1|Subnet|default","region":"australia-southeast1","selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105/regions/australia-southeast1/subnetworks/default"},{"description":null,"gatewayAddress":"10.154.0.1","ipCidrRange":"10.154.0.0/20","network":"default","fingerPrint":"E-w4cgMKubI=","allowSubnetCidrRoutesOverlap":false,"enableFlowLogs":null,"privateIpGoogleAccess":false,"secondaryIpRanges":[],"name":"default","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|Region|europe-west2|Subnet|default","region":"europe-west2","selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105/regions/europe-west2/subnetworks/default"},{"description":null,"gatewayAddress":"10.156.0.1","ipCidrRange":"10.156.0.0/20","network":"default","fingerPrint":"zlc19BjUvKE=","allowSubnetCidrRoutesOverlap":false,"enableFlowLogs":null,"privateIpGoogleAccess":false,"secondaryIpRanges":[],"name":"default","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|Region|europe-west3|Subnet|default","region":"europe-west3","selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105/regions/europe-west3/subnetworks/default"},{"description":null,"gatewayAddress":"10.158.0.1","ipCidrRange":"10.158.0.0/20","network":"default","fingerPrint":"NPxBEcqynWM=","allowSubnetCidrRoutesOverlap":false,"enableFlowLogs":null,"privateIpGoogleAccess":false,"secondaryIpRanges":[],"name":"default","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|Region|southamerica-east1|Subnet|default","region":"southamerica-east1","selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105/regions/southamerica-east1/subnetworks/default"},{"description":null,"gatewayAddress":"10.160.0.1","ipCidrRange":"10.160.0.0/20","network":"default","fingerPrint":"MyN9o2sqYQk=","allowSubnetCidrRoutesOverlap":false,"enableFlowLogs":null,"privateIpGoogleAccess":false,"secondaryIpRanges":[],"name":"default","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|Region|asia-south1|Subnet|default","region":"asia-south1","selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105/regions/asia-south1/subnetworks/default"},{"description":null,"gatewayAddress":"10.162.0.1","ipCidrRange":"10.162.0.0/20","network":"default","fingerPrint":"kLRfCWpEpEQ=","allowSubnetCidrRoutesOverlap":false,"enableFlowLogs":null,"privateIpGoogleAccess":false,"secondaryIpRanges":[],"name":"default","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|Region|northamerica-northeast1|Subnet|default","region":"northamerica-northeast1","selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105/regions/northamerica-northeast1/subnetworks/default"},{"description":null,"gatewayAddress":"10.164.0.1","ipCidrRange":"10.164.0.0/20","network":"default","fingerPrint":"58-Mohn_Grk=","allowSubnetCidrRoutesOverlap":false,"enableFlowLogs":null,"privateIpGoogleAccess":false,"secondaryIpRanges":[],"name":"default","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|Region|europe-west4|Subnet|default","region":"europe-west4","selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105/regions/europe-west4/subnetworks/default"},{"description":null,"gatewayAddress":"10.166.0.1","ipCidrRange":"10.166.0.0/20","network":"default","fingerPrint":"BOWX2SAMBno=","allowSubnetCidrRoutesOverlap":false,"enableFlowLogs":null,"privateIpGoogleAccess":false,"secondaryIpRanges":[],"name":"default","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|Region|europe-north1|Subnet|default","region":"europe-north1","selfLink":"https://www.googleapis.com/compute/beta/projects/serious-conduit-389105/regions/europe-north1/subnetworks/default"},{"description":null,"gatewayAddress":"10.168.0.1","ipCidrRange":"10.168.0.0/20","network":"default","fingerPrint":"O0YjqcPO7n8=","allowSubnetCidrRoutesOverlap":false,"enableFlowLogs":null,"privateIpGoogleAccess":false,"secondaryIpRanges":[],"
