=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_57/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "status": {
            "type": "string"
        },
        "policy": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "description",
                "name"
            ]
        },
        "findingKey": {
            "type": "string"
        },
        "findingId": {
            "type": "string"
        },
        "cloudGuardAccountId": {
            "type": "string"
        },
        "origin": {
            "type": "string"
        },
        "bundle": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            },
            "required": [
                "description",
                "id",
                "name"
            ]
        },
        "reportTime": {
            "type": "string"
        },
        "rule": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "ruleId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "remediation": {
                    "type": "string"
                },
                "complianceTags": {
                    "type": "string"
                },
                "logicHash": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                }
            },
            "required": [
                "complianceTags",
                "description",
                "logicHash",
                "name",
                "remediation",
                "ruleId",
                "severity"
            ]
        },
        "account": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                },
                "dome9CloudAccountId": {
                    "type": "string"
                },
                "organizationalUnitId": {
                    "type": "string"
                },
                "organizationalUnitPath": {
                    "type": "string"
                }
            },
            "required": [
                "dome9CloudAccountId",
                "id",
                "name",
                "organizationalUnitId",
                "organizationalUnitPath",
                "vendor"
            ]
        },
        "region": {
            "type": "string"
        },
        "entity": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "destination": {
                    "type": "string"
                },
                "filter": {
                    "type": "string"
                },
                "storageBucketId": {
                    "type": "null"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "dome9Id": {
                    "type": "string"
                },
                "accountNumber": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "externalFindings": {
                    "type": "string"
                }
            },
            "required": [
                "accountNumber",
                "destination",
                "dome9Id",
                "externalFindings",
                "filter",
                "id",
                "name",
                "region",
                "storageBucketId",
                "type"
            ]
        },
        "remediationActions": {
            "type": "array"
        },
        "action": {
            "type": "string"
        },
        "additionalFields": {
            "type": "array"
        }
    },
    "required": [
        "account",
        "action",
        "additionalFields",
        "bundle",
        "cloudGuardAccountId",
        "entity",
        "findingId",
        "findingKey",
        "origin",
        "policy",
        "region",
        "remediationActions",
        "reportTime",
        "rule",
        "status"
    ]
}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/webhook-1686305239208.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"sCP6g/Ed1BB+wjEJUCs/Aw","findingId":"sCP6g/Ed1BB+wjEJUCs/Aw","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"GCP CloudGuard Best Practices","description":"CloudGuard Best Practices for securing GCP Account","id":-9},"reportTime":"2023-06-09T09:04:54.86Z","rule":{"name":"Ensure that sinks are configured for all log entries","ruleId":"D9.GCP.LOG.28","description":"It is recommended to create a sink that will export copies of all the log entries. This can help aggregate logs from multiple projects and export them to a Security Information and Event Management (SIEM).\nLog entries are held in Cloud Logging. To aggregate logs, export them to a SIEM. To keep them longer, it is recommended to set up a log sink. Exporting involves writing a filter that selects the log entries to export, and choosing a destination in Cloud Storage, BigQuery, or Cloud Pub/Sub. The filter and destination are held in an object called a sink. To ensure all log entries are exported to sinks, ensure that there is no filter configured for a sink. Sinks can be created in projects, organizations, folders, and billing accounts.","remediation":"\n**From Portal**\n1. Go to Logs Router by visiting https://console.cloud.google.com/logs/router\n2. Click on the arrow symbol with CREATE SINK text.\n3. Fill out the fields for Sink details.\n4. Choose Cloud Logging bucket in the Select sink destination drop down menu.\n5. Choose a log bucket in the next drop down menu.\n6. If an inclusion filter is not provided for this sink, all ingested logs will be routed to the destination provided above. This may result in higher than expected resource usage.\n7. Click Create Sink.\n\n**From TF**\nTo create a SINK without filter use resource google_logging_project_sink where you do not need to mention argument filter.\nSee below example;\n```\nresource \"google_logging_project_sink\" \"my-sink\" {\nname = \"my-gcp-sink\"\ndestination  = \"storage.googleapis.com/my-gcp-bucket\"\n}\n```\n\n**From Command Line**\n1. To create a Sink with empty filter matching all entries use;\n```\ngcloud logging sinks create SINK_NAME DESTINATION\n```\n2. for example,To create a sink to export all log entries in a Google Cloud Storage bucket:\n```\ngcloud logging sinks create my-gcp-sink storage.googleapis.com/MY_GCP_BUCKET\n```\n3. Sinks can be created for a folder or organization, which will include all projects.\n```\ngcloud logging sinks create <sink-name> storage.googleapis.com/DESTINATION_BUCKET_NAME --include-children --folder=FOLDER_ID | --organization=ORGANIZATION_ID\n```\n4. A sink created by the command-line above will export logs in storage buckets. However, sinks can be configured to export logs into BigQuery, or Cloud Pub/Sub, or Custom Destination. While creating a sink, the sink option --log-filter is not used to ensure the sink exports all log entries. A sink can be created at a folder or organization level that collects the logs of all the projects underneath bypassing the option --include-children in the gcloud command.\n\n\n**References**\n1. https://cloud.google.com/logging/docs/reference/tools/gcloud-logging\n2. https://cloud.google.com/logging/quotas\n3. https://cloud.google.com/logging/docs/routing/overview\n4. https://cloud.google.com/logging/docs/export/using_exported_logs\n5. https://cloud.google.com/logging/docs/export/configure_export_v2\n6. https://cloud.google.com/logging/docs/export/aggregated_exports\n7. https://cloud.google.com/sdk/gcloud/reference/beta/logging/sinks/list\n8. https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_project_sink","complianceTags":"Logging","logicHash":"9PaoAm07PSyoubDqsHwU4w","severity":"Low"},"account":{"id":"serious-conduit-389105","name":"GCP Demo Account NU","vendor":"GCP","dome9CloudAccountId":"ca5ef528-d8dd-41d8-a022-1a820a6adb60","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"name":"_Default","destination":"logging.googleapis.com/projects/serious-conduit-389105/locations/global/buckets/_Default","filter":"NOT LOG_ID(\"cloudaudit.googleapis.com/activity\") AND NOT LOG_ID(\"externalaudit.googleapis.com/activity\") AND NOT LOG_ID(\"cloudaudit.googleapis.com/system_event\") AND NOT LOG_ID(\"externalaudit.googleapis.com/system_event\") AND NOT LOG_ID(\"cloudaudit.googleapis.com/access_transparency\") AND NOT LOG_ID(\"externalaudit.googleapis.com/access_transparency\")","storageBucketId":null,"id":"_Default","type":"LogSink","dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|logsink|_default","accountNumber":"serious-conduit-389105","region":"Global","externalFindings":"null"},"remediationActions":[],"action":"Detect","additionalFields":[]}
