=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/examples/schema_dir_34/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "status": {
            "type": "string"
        },
        "policy": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "description",
                "name"
            ]
        },
        "findingKey": {
            "type": "string"
        },
        "findingId": {
            "type": "string"
        },
        "cloudGuardAccountId": {
            "type": "string"
        },
        "origin": {
            "type": "string"
        },
        "bundle": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            },
            "required": [
                "description",
                "id",
                "name"
            ]
        },
        "reportTime": {
            "type": "string"
        },
        "rule": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "ruleId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "remediation": {
                    "type": "string"
                },
                "complianceTags": {
                    "type": "string"
                },
                "logicHash": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                }
            },
            "required": [
                "complianceTags",
                "description",
                "logicHash",
                "name",
                "remediation",
                "ruleId",
                "severity"
            ]
        },
        "account": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                },
                "dome9CloudAccountId": {
                    "type": "string"
                },
                "organizationalUnitId": {
                    "type": "string"
                },
                "organizationalUnitPath": {
                    "type": "string"
                }
            },
            "required": [
                "dome9CloudAccountId",
                "id",
                "name",
                "organizationalUnitId",
                "organizationalUnitPath",
                "vendor"
            ]
        },
        "region": {
            "type": "string"
        },
        "entity": {
            "type": "object",
            "properties": {
                "eTag": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                },
                "bindings": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "eTag": {
                                "type": "null"
                            },
                            "role": {
                                "type": "string"
                            },
                            "members": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        },
                        "required": [
                            "eTag",
                            "members",
                            "role"
                        ]
                    }
                },
                "auditConfigs": {
                    "type": "null"
                },
                "selfLink": {
                    "type": "null"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "name": {
                    "type": "null"
                },
                "dome9Id": {
                    "type": "string"
                },
                "accountNumber": {
                    "type": "string"
                },
                "assetLabels": {
                    "type": "null"
                },
                "region": {
                    "type": "string"
                },
                "externalFindings": {
                    "type": "null"
                }
            },
            "required": [
                "accountNumber",
                "assetLabels",
                "auditConfigs",
                "bindings",
                "dome9Id",
                "eTag",
                "externalFindings",
                "id",
                "name",
                "region",
                "selfLink",
                "type",
                "version"
            ]
        },
        "remediationActions": {
            "type": "array"
        },
        "action": {
            "type": "string"
        },
        "additionalFields": {
            "type": "array"
        }
    },
    "required": [
        "account",
        "action",
        "additionalFields",
        "bundle",
        "cloudGuardAccountId",
        "entity",
        "findingId",
        "findingKey",
        "origin",
        "policy",
        "region",
        "remediationActions",
        "reportTime",
        "rule",
        "status"
    ]
}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/webhook-1686305226486.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"IUkE5efmdY5ymyDQMHoUeg","findingId":"IUkE5efmdY5ymyDQMHoUeg","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"GCP CloudGuard Best Practices","description":"CloudGuard Best Practices for securing GCP Account","id":-9},"reportTime":"2023-06-09T09:04:54.86Z","rule":{"name":"Avoid using pre-IAM basic (primitive) roles","ruleId":"D9.GCP.IAM.12","description":"Basic roles include many permissions across all GCP services. Using them will result violation of the principle of least privilege. You should avoid using basic roles, and use predefined roles or custom roles instead.","remediation":"\n**From Portal**\n1. Go to IAM & admin/IAM using https://console.cloud.google.com/iam-admin/iam\n2. Go to the Principals\n3. Identify the member with the owner/basic roles, add the roles that each member needs while following the principle of least privilege, then remove any owner/editor roles.\n\n\n**From Command Line**\n1. Get the projects policy and write it to a yaml file,Run:\n```\ngcloud projects get-iam-policy PROJECT_ID PATH_TO_NEWLY_CREATED_FILE\n```\n2. In the created yaml add the roles that each member needs while following the principle of least privilege, then remove owner/editor roles.\n3. Set the new iam policy:\n```\ngcloud projects set-iam-policy PROJECT_ID PATH_TO_EDITED_FILE\n```\n\n**References**\n1. https://cloud.google.com/sdk/gcloud/reference/projects/get-iam-policy\n2. https://cloud.google.com/sdk/gcloud/reference/projects/set-iam-policy\n3. https://cloud.google.com/iam/docs/understanding-roles\n4. https://cloud.google.com/iam/docs/permissions-reference","complianceTags":"Identity and Access Management","logicHash":"+kx5hYR8kFpf2rhf+kFnTQ","severity":"High"},"account":{"id":"serious-conduit-389105","name":"GCP Demo Account NU","vendor":"GCP","dome9CloudAccountId":"ca5ef528-d8dd-41d8-a022-1a820a6adb60","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"eTag":"BwX9lAgKdAg=","version":1,"bindings":[{"eTag":null,"role":"roles/cloudasset.viewer","members":["serviceAccount:cloudguard-connect@serious-conduit-389105.iam.gserviceaccount.com"]},{"eTag":null,"role":"roles/cloudfunctions.serviceAgent","members":["serviceAccount:service-554880214893@gcf-admin-robot.iam.gserviceaccount.com"]},{"eTag":null,"role":"roles/compute.serviceAgent","members":["serviceAccount:service-554880214893@compute-system.iam.gserviceaccount.com"]},{"eTag":null,"role":"roles/container.serviceAgent","members":["serviceAccount:service-554880214893@container-engine-robot.iam.gserviceaccount.com"]},{"eTag":null,"role":"roles/containerregistry.ServiceAgent","members":["serviceAccount:service-554880214893@containerregistry.iam.gserviceaccount.com"]},{"eTag":null,"role":"roles/editor","members":["serviceAccount:554880214893-compute@developer.gserviceaccount.com","serviceAccount:554880214893@cloudservices.gserviceaccount.com","serviceAccount:serious-conduit-389105@appspot.gserviceaccount.com"]},{"eTag":null,"role":"roles/file.serviceAgent","members":["serviceAccount:service-554880214893@cloud-filer.iam.gserviceaccount.com"]},{"eTag":null,"role":"roles/iam.securityReviewer","members":["serviceAccount:cloudguard-connect@serious-conduit-389105.iam.gserviceaccount.com"]},{"eTag":null,"role":"roles/memcache.serviceAgent","members":["serviceAccount:service-554880214893@cloud-memcache-sa.iam.gserviceaccount.com"]},{"eTag":null,"role":"roles/owner","members":["user:nils@nilsujma.io"]},{"eTag":null,"role":"roles/pubsub.serviceAgent","members":["serviceAccount:service-554880214893@gcp-sa-pubsub.iam.gserviceaccount.com"]},{"eTag":null,"role":"roles/redis.serviceAgent","members":["serviceAccount:service-554880214893@cloud-redis.iam.gserviceaccount.com"]},{"eTag":null,"role":"roles/viewer","members":["serviceAccount:cloudguard-connect@serious-conduit-389105.iam.gserviceaccount.com"]}],"auditConfigs":null,"selfLink":null,"id":"IAM-POLICY-serious-conduit-389105","type":"GcpIamPolicy","name":null,"dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|IamPolicy","accountNumber":"serious-conduit-389105","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}

=== nilsujma-dev/CloudGuard-JSON-to-CEF-Converter/webhook-1686305214836.json
{"status":"Failed","policy":{"name":"Webhooks","description":""},"findingKey":"9OyYz5hEe8M0jDDcH/J3SA","findingId":"9OyYz5hEe8M0jDDcH/J3SA","cloudGuardAccountId":"51722","origin":"Compliance Engine","bundle":{"name":"GCP CloudGuard Best Practices","description":"CloudGuard Best Practices for securing GCP Account","id":-9},"reportTime":"2023-06-09T09:04:54.86Z","rule":{"name":"Ensure that Cloud Audit Logging is configured properly across all services and all users from a project","ruleId":"D9.GCP.LOG.18","description":"It is recommended that Cloud Audit Logging is configured to track all admin activities and read, write access to user data.\nCloud Audit Logging maintains two audit logs for each project, folder, and organization- Admin Activity and Data Access.\n1. Admin Activity logs contain log entries for API calls or other administrative actions that modify the configuration or metadata of resources. Admin Activity audit logs are enabled for all services and cannot be configured.\n2. Data Access audit logs record API calls that create, modify, or read user-provided data. These are disabled by default and should be enabled.\nThere are three kinds of Data Access audit log information:\n1.Admin read- Records operations that read metadata or configuration information. Admin Activity audit logs record writes of metadata and configuration information that cannot be disabled.\n2.Data read- Records operations that read user-provided data.\n3.Data write- Records operations that write user-provided data.\nIt is recommended to have an effective default audit config configured in such a way that:\n1.logtype is set to DATA_READ (to log user activity tracking) and DATA_WRITES (to log changes/tampering to user data).\n2.audit config is enabled for all the services supported by the Data Access audit logs feature.\n3.Logs should be captured for all users, i.e., there are no exempted users in any of the audit config sections. This will ensure overriding the audit config will not contradict the requirement.","remediation":"\n**From Portal**\n1. Go to Audit Logs by visiting https://console.cloud.google.com/iam-admin/audit.\n2. Click on Default Audit Config at the top of the page.\n3. In the 'LOG TYPE' tab, select the check boxes Admin Read, Data Read, and Data Write, and click Save(All check boxes).\n4. In the 'EXEMPTED USERS' tab, remove all users if any. Click Save.\n\n**From Command Line**\n1. To read the project's IAM policy and store it in a file run a command:\n```\ngcloud projects get-iam-policy PROJECT_ID > /tmp/project_policy.yaml\n```\nAlternatively, the policy can be set at the organization or folder level. If setting the policy at the organization level, it is not necessary to also set it for each folder or project.\n\n```\ngcloud organizations get-iam-policy ORGANIZATION_ID > /tmp/org_policy.yaml\ngcloud resource-manager folders get-iam-policy FOLDER_ID > /tmp/folder_policy.yaml\n```\n2. Edit policy in /tmp/policy.yaml, adding or changing only the audit logs configuration to:\n```\nauditConfigs:\n- auditLogConfigs:\n- logType: ADMIN_READ\n- logType: DATA_WRITE\n- logType: DATA_READ\nservice: allServices\n```\nNote: exemptedMembers: is not set as audit logging should be enabled for all the users.\n\n3. To write new IAM policy run command:\n```\ngcloud organizations set-iam-policy ORGANIZATION_ID /tmp/org_policy.yaml\ngcloud resource-manager folders set-iam-policy FOLDER_ID /tmp/folder_policy.yaml\ngcloud projects set-iam-policy PROJECT_ID /tmp/project_policy.yaml\n\n```\nIf the preceding command reports a conflict with another change, then repeat these steps, starting with the first step.\n\n**From TF**\n1. Make sure you have following values in the template for the mentioned resource and there should not be any exempted_members for any audit_log_config.\nResource: google_project_iam_audit_config\n\n```\nresource \"google_project_iam_audit_config\" \"project\" {\nproject = \"your-project-id\"\nservice = \"allServices\"\naudit_log_config {\nlog_type = \"ADMIN_READ\"\n}\naudit_log_config {\nlog_type = \"DATA_WRITE\"\n}\naudit_log_config {\nlog_type = \"DATA_READ\"\n}\n}\n\n```\n\n**References**\n1. https://cloud.google.com/logging/docs/audit/\n2. https://cloud.google.com/logging/docs/audit/configure-data-access\n3. https://workbench.cisecurity.org/sections/507170/recommendations/827546\n4. https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam ","complianceTags":"Logging","logicHash":"Sn0ltJbGiZuRBHODu/w8aw","severity":"Low"},"account":{"id":"serious-conduit-389105","name":"GCP Demo Account NU","vendor":"GCP","dome9CloudAccountId":"ca5ef528-d8dd-41d8-a022-1a820a6adb60","organizationalUnitId":"00000000-0000-0000-0000-000000000000","organizationalUnitPath":""},"region":"Global","entity":{"eTag":"BwX9lAgKdAg=","version":1,"bindings":[{"eTag":null,"role":"roles/cloudasset.viewer","members":["serviceAccount:cloudguard-connect@serious-conduit-389105.iam.gserviceaccount.com"]},{"eTag":null,"role":"roles/cloudfunctions.serviceAgent","members":["serviceAccount:service-554880214893@gcf-admin-robot.iam.gserviceaccount.com"]},{"eTag":null,"role":"roles/compute.serviceAgent","members":["serviceAccount:service-554880214893@compute-system.iam.gserviceaccount.com"]},{"eTag":null,"role":"roles/container.serviceAgent","members":["serviceAccount:service-554880214893@container-engine-robot.iam.gserviceaccount.com"]},{"eTag":null,"role":"roles/containerregistry.ServiceAgent","members":["serviceAccount:service-554880214893@containerregistry.iam.gserviceaccount.com"]},{"eTag":null,"role":"roles/editor","members":["serviceAccount:554880214893-compute@developer.gserviceaccount.com","serviceAccount:554880214893@cloudservices.gserviceaccount.com","serviceAccount:serious-conduit-389105@appspot.gserviceaccount.com"]},{"eTag":null,"role":"roles/file.serviceAgent","members":["serviceAccount:service-554880214893@cloud-filer.iam.gserviceaccount.com"]},{"eTag":null,"role":"roles/iam.securityReviewer","members":["serviceAccount:cloudguard-connect@serious-conduit-389105.iam.gserviceaccount.com"]},{"eTag":null,"role":"roles/memcache.serviceAgent","members":["serviceAccount:service-554880214893@cloud-memcache-sa.iam.gserviceaccount.com"]},{"eTag":null,"role":"roles/owner","members":["user:nils@nilsujma.io"]},{"eTag":null,"role":"roles/pubsub.serviceAgent","members":["serviceAccount:service-554880214893@gcp-sa-pubsub.iam.gserviceaccount.com"]},{"eTag":null,"role":"roles/redis.serviceAgent","members":["serviceAccount:service-554880214893@cloud-redis.iam.gserviceaccount.com"]},{"eTag":null,"role":"roles/viewer","members":["serviceAccount:cloudguard-connect@serious-conduit-389105.iam.gserviceaccount.com"]}],"auditConfigs":null,"selfLink":null,"id":"IAM-POLICY-serious-conduit-389105","type":"GcpIamPolicy","name":null,"dome9Id":"8|ca5ef528-d8dd-41d8-a022-1a820a6adb60|IamPolicy","accountNumber":"serious-conduit-389105","assetLabels":null,"region":"Global","externalFindings":null},"remediationActions":[],"action":"Detect","additionalFields":[]}
